### PR TITLE
Fix snapshots of uVMs with PATCHed block devices

### LINKED ISSUE #1974: InvalidOffset (virtio-block) error when resuming after loading a snapshot (with rootfs from firecracker-containerd)
Hi, we started developing support for snapshot `pause/resume/create/load` inside our fork of firecracker-containerd (we can make the code public). While we had no problem with supporting `pause/resume/create-snapshot` methods we ran into an error inside Firecracker's virtio-block module with `load-snapshot->resume`.

The workflow is startVM(boot) -> Pause -> Create-Snap -> Offload (kill the VM with SIGTERM) -> SnapshotLoad -> Resume

The problem we face is at the Resume point where we get the following error from firecracker's log:
```
2020-06-25T07:21:10.652265445 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/snapshot/load" with body "{\"mem_file_path\":\"/tmp/mem_file\",\"snapshot_path\":\"/tmp/snapshot_file\"}".
2020-06-25T07:21:10.664695532 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:21:10.665787599 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Patch request on "/vm" with body "{\"state\":\"Resumed\"}".
2020-06-25T07:21:10.665908820 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:21:14.799994834 [anonymous-instance:ERROR:src/devices/src/virtio/block/device.rs:226] Failed to execute request: BadRequest(InvalidOffset)
2020-06-25T07:21:14.802628426 [anonymous-instance:ERROR:src/devices/src/virtio/block/device.rs:226] Failed to execute request: BadRequest(InvalidOffset)
```

We tend to think that this can be related to the way firecracker-containerd manages block devices.  The VM mounts block devices in 2 phases. First, the VM boots from a generic rootfs (with the containerd agent):
```
The API server received a Put request on "/drives/root_drive" with body "The API server received a Put request on "/drives/root_drive" with body "{\"drive_id\":\"root_drive\",\"is_read_only\":true,\"is_root_device\":true,\"path_on_host\":\"/var/lib/firecracker-containerd/runtime/default-rootfs.img\"}\n".
```
Then the agent needs to mount a second block device that contains the container-specific data. To do so, containerd attaches another drive and patches the path to the drive twice:
```
The API server received a Put request on "/drives/MN2HE43UOVRDA" with body "{\"drive_id\":\"MN2HE43UOVRDA\",\"is_read_only\":false,\"is_root_device\":false,\"path_on_host\":\"/var/lib/firecracker-containerd/shim-base/firecracker-containerd/505/ctrstub0\"}\n".
<<..>>
The API server received a Put request on "/actions" with body "{\"action_type\":\"InstanceStart\"}\n".
The request was executed successfully. Status code: 204 No Content.
The API server received a Patch request on "/drives/MN2HE43UOVRDA" with body "{\"drive_id\":\"MN2HE43UOVRDA\",\"path_on_host\":\"/dev/mapper/fc-dev-thinpool-snap-9\"}\n".
```

Can the issue be connected to the way [PATCH drive works](https://github.com/firecracker-microvm/firecracker/blob/master/docs/api_requests/patch-block.md)? This drive is supposed to remain mounted into the restored guest.

We would greatly appreciate comments and ideas on what could be the root cause from Firecracker and firecracker-containerd maintainers: for example, @acatangiu @kzys . Once we fix the issue, we would be happy to contribute our changes to firecracker-containerd upstream.

Full workflow log (Firecracker's log):
```
Running Firecracker v0.21.0
2020-06-25T07:20:17.287742839 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.288144594 [anonymous-instance:INFO] The API server received a Put request on "/machine-config" with body "{\"cpu_template\":\"T2\",\"ht_enabled\":false,\"mem_size_mib\":512,\"vcpu_count\":1}\n".
2020-06-25T07:20:17.288291418 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.288521865 [anonymous-instance:INFO] The API server received a Get request on "/machine-config".
2020-06-25T07:20:17.288625819 [anonymous-instance:INFO] The request was executed successfully. Status code: 200 OK.
2020-06-25T07:20:17.288971127 [anonymous-instance:INFO] The API server received a Put request on "/boot-source" with body "{\"boot_args\":\"8250.nr_uarts=0 ip=190.128.0.2::190.128.0.1:255.192.0.0:::off::: systemd.log_color=false init=/sbin/overlay-init systemd.unit=firecracker.target quiet noapic nomodules ipv6.disable=1 ro panic=1 tsc=reliable reboot=k pci=off\",\"kernel_image_path\":\"/var/lib/firecracker-containerd/runtime/hello-vmlinux.bin\"}\n".
2020-06-25T07:20:17.289115444 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.289571124 [anonymous-instance:INFO] The API server received a Put request on "/drives/root_drive" with body "{\"drive_id\":\"root_drive\",\"is_read_only\":true,\"is_root_device\":true,\"path_on_host\":\"/var/lib/firecracker-containerd/runtime/default-rootfs.img\"}\n".
2020-06-25T07:20:17.289732138 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.290046499 [anonymous-instance:INFO] The API server received a Put request on "/drives/MN2HE43UOVRDA" with body "{\"drive_id\":\"MN2HE43UOVRDA\",\"is_read_only\":false,\"is_root_device\":false,\"path_on_host\":\"/var/lib/firecracker-containerd/shim-base/firecracker-containerd/505/ctrstub0\"}\n".
2020-06-25T07:20:17.290151860 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.290522553 [anonymous-instance:INFO] The API server received a Put request on "/network-interfaces/1" with body "{\"guest_mac\":\"02:FC:00:00:00:00\",\"host_dev_name\":\"fc-0-tap0\",\"iface_id\":\"1\"}\n".
2020-06-25T07:20:17.292898333 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.293236487 [anonymous-instance:INFO] The API server received a Put request on "/vsock" with body "{\"guest_cid\":0,\"uds_path\":\"firecracker.vsock\",\"vsock_id\":\"agent_api\"}\n".
2020-06-25T07:20:17.293472939 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:17.293754191 [anonymous-instance:INFO] The API server received a Put request on "/actions" with body "{\"action_type\":\"InstanceStart\"}\n".
2020-06-25T07:20:17.305625745 [anonymous-instance:WARN] Could not add serial input event to epoll: Error during epoll call: Operation not permitted (os error 1)
2020-06-25T07:20:17.306309907 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:19.177877690 [anonymous-instance:INFO] The API server received a Patch request on "/drives/MN2HE43UOVRDA" with body "{\"drive_id\":\"MN2HE43UOVRDA\",\"path_on_host\":\"/dev/mapper/fc-dev-thinpool-snap-9\"}\n".
2020-06-25T07:20:19.178152684 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:20.104482947 [anonymous-instance:INFO] The API server received a Patch request on "/vm" with body "{\"state\":\"Paused\"}".
2020-06-25T07:20:20.104702379 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.
2020-06-25T07:20:20.106119166 [anonymous-instance:INFO] The API server received a Put request on "/snapshot/create" with body "{\"mem_file_path\":\"/tmp/mem_file\",\"snapshot_path\":\"/tmp/snapshot_file\",\"snapshot_type\":\"Full\"}".
2020-06-25T07:20:20.649402863 [anonymous-instance:INFO] The request was executed successfully. Status code: 204 No Content.

```

And the corresponding log from firecracker-containerd (containerd's log)
```
INFO[2020-06-25T07:20:17.275031352-04:00] creating new VM                               runtime=aws.firecracker vmID=505
ERRO[2020-06-25T07:20:17.275464729-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Called startVMM(), setting up a VMM on firecracker.sock"  shim_stream=stderr vmID=505
setupLogging
setupMetrics
ERRO[2020-06-25T07:20:17.288041835-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="VMM metrics disabled."  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.288909406-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="refreshMachineConfiguration: [GET /machine-config][200] getMachineConfigurationOK  &{CPUTemplate:T2 HtEnabled:0xc000582f43 MemSizeMib:0xc000582f38 VcpuCount:0xc000582f30}"  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.289306935-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="PutGuestBootSource: [PUT /boot-source][204] putGuestBootSourceNoContent "  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.289343891-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Attaching drive /var/lib/firecracker-containerd/runtime/default-rootfs.img, slot root_drive, root true."  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.289933498-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Attached drive /var/lib/firecracker-containerd/runtime/default-rootfs.img: [PUT /drives/{drive_id}][204] putGuestDriveByIdNoContent "  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.289952823-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Attaching drive /var/lib/firecracker-containerd/shim-base/firecracker-containerd/505/ctrstub0, slot MN2HE43UOVRDA, root false."  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.290347821-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Attached drive /var/lib/firecracker-containerd/shim-base/firecracker-containerd/505/ctrstub0: [PUT /drives/{drive_id}][204] putGuestDriveByIdNoContent "  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:17.290377745-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="Attaching NIC fc-0-tap0 (hwaddr 02:FC:00:00:00:00) at index 1"  shim_stream=stderr vmID=505
INFO[2020-06-25T07:20:17.306497334-04:00] calling agent                                 runtime=aws.firecracker vmID=505
ERRO[2020-06-25T07:20:17.306529875-04:00] time="2020-06-25T07:20:17-04:00" level=info msg="startInstance successful: [PUT /actions][204] createSyncActionNoContent "  shim_stream=stderr vmID=505
DEBU[2020-06-25T07:20:18.004394761-04:00] garbage collected                             d=10.79516ms
INFO[2020-06-25T07:20:18.410674791-04:00] successfully started the VM                   runtime=aws.firecracker vmID=505
DEBU[2020-06-25T07:20:18.411052023-04:00] event forwarded                               ns=firecracker-containerd topic=/firecracker-vm/start type=VMStart
DEBU[2020-06-25T07:20:18.440217583-04:00] prepare snapshot                              key=505 parent="sha256:0065b13862ce3af1bf002db326cc2c0a1245165cf6ae7f22abaceae55e09f6fc"
DEBU[2020-06-25T07:20:18.440347865-04:00] prepare                                       key=firecracker-containerd/17/505 parent="firecracker-containerd/16/sha256:0065b13862ce3af1bf002db326cc2c0a1245165cf6ae7f22abaceae55e09f6fc"
DEBU[2020-06-25T07:20:18.440504004-04:00] creating snapshot device 'fc-dev-thinpool-snap-9' from 'fc-dev-thinpool-snap-8' 
DEBU[2020-06-25T07:20:18.795683399-04:00] event published                               ns=firecracker-containerd topic=/snapshot/prepare type=containerd.events.SnapshotPrepare
DEBU[2020-06-25T07:20:18.800390309-04:00] get snapshot mounts                           key=505
DEBU[2020-06-25T07:20:18.800469759-04:00] mounts                                        key=firecracker-containerd/17/505
DEBU[2020-06-25T07:20:19.120516743-04:00] event published                               ns=firecracker-containerd topic=/containers/create type=containerd.events.ContainerCreate
DEBU[2020-06-25T07:20:19.138167895-04:00] get snapshot mounts                           key=505
DEBU[2020-06-25T07:20:19.138206395-04:00] mounts                                        key=firecracker-containerd/17/505
time="2020-06-25T07:20:19.174115148-04:00" level=debug msg=StartShim runtime=aws.firecracker task_id=505
DEBU[2020-06-25T07:20:19.175656280-04:00] create VM request: VMID:"505"                
DEBU[2020-06-25T07:20:19.175707632-04:00] using namespace: firecracker-containerd      
time="2020-06-25T07:20:19.176188684-04:00" level=info msg="successfully started shim (git commit: 22b7cfceb4901b91c998a380df74d9b825614967)." runtime=aws.firecracker task_id=505 vmID=505
ERRO[2020-06-25T07:20:19.178386061-04:00] time="2020-06-25T07:20:19-04:00" level=info msg="PatchGuestDrive successful"  shim_stream=stderr vmID=505
INFO[2020-06-25T07:20:19.330752483-04:00] successfully created task                     ExecID= TaskID=505 pid_in_vm=727 runtime=aws.firecracker vmID=505
DEBU[2020-06-25T07:20:19.331251986-04:00] event forwarded                               ns=firecracker-containerd topic=/tasks/create type=containerd.events.TaskCreate
DEBU[2020-06-25T07:20:19.337046160-04:00] garbage collected                             d=12.841932ms
DEBU[2020-06-25T07:20:19.339260338-04:00] event forwarded                               ns=firecracker-containerd topic=/tasks/start type=containerd.events.TaskStart
DEBU[2020-06-25T07:20:20.103637583-04:00] pause VM request: VMID:"505"                 
DEBU[2020-06-25T07:20:20.105566980-04:00] make snapshot request: VMID:"505" SnapshotFilePath:"/tmp/snapshot_file" MemFilePath:"/tmp/mem_file"  
DEBU[2020-06-25T07:20:20.650066779-04:00] offload original request: VMID:"505"         
ERRO[2020-06-25T07:20:25.892253044-04:00] error waiting for exit                        ExecID= TaskID=505 error="ttrpc: closed" runtime=aws.firecracker vmID=505
ERRO[2020-06-25T07:20:25.892257191-04:00] error while forwarding events from VM agent   error="ttrpc: closed" runtime=aws.firecracker vmID=505
ERRO[2020-06-25T07:20:25.892484333-04:00] error copying io                              ExecID= TaskID=505 error="reading from a closed fifo" runtime=aws.firecracker stream=stdin vmID=505
ERRO[2020-06-25T07:20:25.892580185-04:00] error closing io stream                       ExecID= TaskID=505 error="1 error occurred:\n\t* close unix @->firecracker.vsock: use of closed network connection\n\n" runtime=aws.firecracker stream=stdin vmID=505
ERRO[2020-06-25T07:20:25.923729272-04:00] time="2020-06-25T07:20:25-04:00" level=warning msg="firecracker exited: signal: killed"  shim_stream=stderr vmID=505
ERRO[2020-06-25T07:20:30.892486598-04:00] error closing io stream                       ExecID= TaskID=505 error="1 error occurred:\n\t* close unix @->firecracker.vsock: use of closed network connection\n\n" runtime=aws.firecracker stream=stderr vmID=505
ERRO[2020-06-25T07:20:30.892525517-04:00] error closing io stream                       ExecID= TaskID=505 error="1 error occurred:\n\t* close unix @->firecracker.vsock: use of closed network connection\n\n" runtime=aws.firecracker stream=stdout vmID=505
DEBU[2020-06-25T07:21:10.651353555-04:00] load snapshot request: VMID:"505" SnapshotFilePath:"/tmp/snapshot_file" MemFilePath:"/tmp/mem_file"  
DEBU[2020-06-25T07:21:10.665366928-04:00] resume VM request: VMID:"505" 
```

Platform: Host: Ubuntu 18, v4.15. Guest: containerd's default kernel and rootfs

### PR DESCRIPTION
**Pull request by acatangiu**
## Draft status

Needs regression test before upgrading to mergeable PR.

## Reason for This PR

Fixes #1974 

## Description of Changes

When doing a Block device backing file update we have to update multiple properties built from the backing file.

The actual backing file path was not being updated so snapshots would use the old path and snapshot restores would malfunction.

Created `DiskProperties` helper object for setting up all `Block` fields derived from the backing file. The object can be used in both construction and update paths for the `Block` device.
It provides functionality for setting up all backing file related fields so that all related logic is contained.

This commit fixes snapshots of uVMs with PATCHed block devices.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

File: src/devices/src/virtio/block/device.rs [hunk 1]
```diff
@@ -117,12 +149,7 @@ impl Block {
         is_disk_root: bool,
         rate_limiter: RateLimiter,
     ) -> io::Result<Block> {
-        let mut disk_image = OpenOptions::new()
-            .read(true)
-            .write(!is_disk_read_only)
-            .open(PathBuf::from(&disk_image_path))?;
-
-        let disk_size = disk_image.seek(SeekFrom::End(0))? as u64;
+        let disk_image = DiskProperties::new(disk_image_path, is_disk_read_only)?;
```
Comment (sandreim) [inline src/devices/src/virtio/block/device.rs:152]: Would make sense to rename this to disk_properties.

File: src/devices/src/virtio/block/device.rs [hunk 2]
```diff
@@ -29,61 +29,93 @@ use super::{
...
-        Err(_) => {
-            warn!("Could not generate device id. We'll use a default.");
+    /// Provides vec containing the virtio block configuration space
+    /// buffer. The config space is populated with the disk size based
+    /// on the backing file size.
+    pub fn virtio_block_config_space(&self) -> Vec<u8> {
+        // We only support disk size, which uses the first two words of the configuration space.
+        // If the image is not a multiple of the sector size, the tail bits are not exposed.
+        // The config space is little endian.
+        if self.size % SECTOR_SIZE != 0 {
```
Comment (sandreim) [inline src/devices/src/virtio/block/device.rs:99]: I would move this check to the constructor and then we can just keep `nsectors` and drop the `size` field.

File: src/devices/src/virtio/block/device.rs [hunk 3]
```diff
@@ -490,6 +510,26 @@ pub(crate) mod tests {
         assert_eq!(b.interrupt_evt.read().unwrap(), 1);
     }
 
+    #[test]
+    fn test_disk_backing_file_helper() {
```
Comment (sandreim) [inline src/devices/src/virtio/block/device.rs:514]: A negative test for disk properties would make sense here.

Comment (acatangiu) [reply src/devices/src/virtio/block/device.rs:514]: What kind of negative test do you have in mind? I'm coming up blank :see_no_evil:

File: src/devices/src/virtio/block/device.rs (hunk 2 above)
Comment (acatangiu) [reply src/devices/src/virtio/block/device.rs:99]: Right, done.

File: src/devices/src/virtio/block/device.rs (hunk 1 above)
Comment (acatangiu) [reply src/devices/src/virtio/block/device.rs:152]: Oki, done.

File: src/devices/src/virtio/block/device.rs (hunk 3 above)
Comment (acatangiu) [reply src/devices/src/virtio/block/device.rs:512]: Done.

File: tests/framework/builder.py [hunk 4]
```diff
@@ -121,7 +123,7 @@ def __init__(self, microvm):
         self._microvm = microvm
 
     def create(self,
-               disks: [DiskArtifact],
+               disks,
```
Comment (sandreim) [inline tests/framework/builder.py:126]: why remove type hint ?

File: tests/integration_tests/functional/test_snapshot_basic.py [hunk 5]
```diff
@@ -104,6 +138,47 @@ def _test_seq_snapshots(context):
...
+
+    # Create the test matrix.
+    test_matrix = TestMatrix(context=test_context,
+                             artifact_sets=[
+                                 microvm_artifacts,
+                                 kernel_artifacts,
+                                 disk_artifacts
+                             ])
+
+    test_matrix.run_test(_test_seq_snapshots)
```
Comment (sandreim) [inline tests/integration_tests/functional/test_snapshot_basic.py:179]: Looks like `_test_seq_snapshots` is quickly becoming a "god" test fn 😄 . I would just create another separate simple test. 

Or do you think it is worth to complicate it and avoid duplicating code ?

File: tests/framework/builder.py (hunk 4 above)
Comment (acatangiu) [reply tests/framework/builder.py:126]: because it's no longer a list of `Artifacts`, it's currently a list of disk local paths, but it can be a list of different objects really, no need to tie it to a specific type.

File: tests/integration_tests/functional/test_snapshot_basic.py (hunk 5 above)
Comment (acatangiu) [reply tests/integration_tests/functional/test_snapshot_basic.py:179]: I read it as a general (`god`) function that will run different `context`s. To me it doesn't look too big or complex right now, but we could duplicate the common parts and split it in specialized functions if you think it makes more sense.

File: src/devices/src/virtio/block/device.rs [hunk 6]
```diff
@@ -267,14 +289,10 @@ impl Block {
     }
 
     /// Update the backing file for the Block device.
```
Comment (ioanachirca) [inline src/devices/src/virtio/block/device.rs:291]: Update the comment: `Update the backing file and the config space of the block device`.

File: tests/framework/microvm.py [hunk 7]
```diff
@@ -521,6 +521,24 @@ def basic_config(
...
+        response = self.drive.put(
+            drive_id=drive_id,
+            path_on_host=self.create_jailed_resource(file.path),
+            is_root_device=root_device,
+            is_read_only=is_read_only
+        )
+        assert self.api_session.is_status_no_content(response.status_code)
+
+    def patch_drive(self, drive_id, file):
+        """Modify/patch an existing a block device."""
```
Comment (ioanachirca) [inline tests/framework/microvm.py:535]: nit:
```suggestion
        """Modify/patch an existing block device."""
```

File: tests/integration_tests/functional/test_snapshot_basic.py (hunk 5 above)
Comment (ioanachirca) [reply tests/integration_tests/functional/test_snapshot_basic.py:179]: The part where a second scratch disk is added is not very general. I'm in favor of moving the common parts to separate methods, and having different test functions for each usecase instead of checking a lot of context flags in `_test_seq_snapshots`. For example, for verifying that patching the block device works we don't need to also run `fio`.

Comment (acatangiu) [reply tests/integration_tests/functional/test_snapshot_basic.py]: done.

File: tests/integration_tests/functional/test_snapshot_basic.py [hunk 8]
```diff
@@ -104,6 +200,44 @@ def _test_seq_snapshots(context):
...
+    # Create a test context and add builder, logger, network.
+    test_context = TestContext()
+    test_context.custom = {
+        'builder': MicrovmBuilder(bin_cloner_path),
+        'network_config': network_config,
+        'logger': logger
+    }
+
+    # Create the test matrix.
+    test_matrix = TestMatrix(context=test_context,
```
Comment (sandreim) [inline tests/integration_tests/functional/test_snapshot_basic.py:231]: Looks like the test matrix produces only 1 run configuration. I think you can drop the TestMatrix and move _test_patch_drive_snapshot code here.

Comment (acatangiu) [reply tests/integration_tests/functional/test_snapshot_basic.py:231]: synced offline and decided to keep it like this since `TestMatrix` is responsible for downloading artifacts.

We plan to add microvm 'recipes' that download relevant artifacts and use them to replace current fixtures in a future PR.

**Comment by acatangiu** [comment]
> nit: you're adding the PATCH drive test in the existing seq snapshot test and then moving it in a separate test in another commit. I would directly add the specific test and not go through altering the existing one

Yes, this was for easier reviewing so we can decide on which option we want, the plan was to squash them eventually but I forgot :see_no_evil:
