### PR TITLE
jailer: fix perf regression when closing open FDs

### LINKED ISSUE #3542: [Bug] Firecracker uses up 100% CPU after an upgrade from v1.1.2 to v1.3.1
# Describe the bug

After upgrading firecracker from v1.1.2 to v1.3.1 the VMM instantly uses up 100% of the CPU while not creating an unix api socket. Firecracker eventually manages to create the socket, but it takes a few minutes. After attaching to the faulty firecracker process with `strace` it is revealed that firecracker is stuck in a loop trying to close every pid in existence:
image

## To Reproduce

Run firecracker inside a privileged docker container based on `node:16-bullseye` with `/dev/kvm` mounted inside.  v1.1.2 works fine,  v1.3.1 doesn't work at all.

## Expected behaviour

The Firecracker process starts without using 100% of the CPU and creates an unix socket.

## Environment
 - Firecracker version: v1.3.1
- Host kernel: 6.1.12-arch1-1 Archlinux
- Guest kernel: 5.6
- Rootfs used: Ext4, ubuntu 22.04
- Architecture: x86_64, AMD Ryzen 9 5950X

## Additional context
I was working on my startup which is a project for creating and managing dev environments inside Firecracker Microvm's. The project works fine using firecracker v1.1.2, after I upgraded the firecracker version the project broke.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by dianpopa**
## Changes

Fixes the mechanism for closing open FDs in jailer which was
based on the SC_OPEN_MAX system constant. Such an approach can lead
to bad performance when this value is very high.

The method for closing file descriptors is now chosen based on the environment:
 1. we try to call into the close_range syscall (available on kernels >=5.9)
 2. we fallback to reading from /proc/self/fd (for kernels <5.9)
    
 ## Reason

Fixes #3542 - a bug where firecracker would end up spending minutes starting which arises when running on systems with OPEN_MAX set to a very high number.

Thanks @gorbak25 for reporting the issue and proposing the fix!

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

File: src/jailer/src/main.rs [hunk 1]
```diff
@@ -235,21 +244,71 @@ pub fn readln_special<T: AsRef<Path>>(file_path: &T) -> Result<String> {
...
+    )
+    .map_err(|e| Error::DirOpen(path.to_string(), e.to_string()))?;
+
+    let dirfd = dir.as_raw_fd();
+    let mut c = dir.iter();
+
+    while let Some(Ok(path)) = c.next() {
+        let file_name = path.file_name();
+        let fd_str = file_name.to_str().map_err(Error::UTF8Parsing)?;
+        println!("fd_str is {}", fd_str);
```
Comment (luminitavoicu) [inline src/jailer/src/main.rs:280]: Leftover?

File: src/jailer/src/main.rs [hunk 2]
```diff
@@ -235,21 +244,71 @@ pub fn readln_special<T: AsRef<Path>>(file_path: &T) -> Result<String> {
...
+    SyscallReturnCode(unsafe {
+        libc::syscall(
+            libc::SYS_close_range,
+            3,
+            libc::c_uint::MAX,
+            libc::CLOSE_RANGE_UNSHARE,
+        )
+    } as libc::c_int)
+    .into_empty_result()
+    .map_err(Error::CloseRange)
```
Comment (luminitavoicu) [inline src/jailer/src/main.rs:259]: Nit: do we need this dedicated error since we discard the error when this call fails and we have a fallback mechanism?

File: src/jailer/src/main.rs [hunk 3]
```diff
@@ -235,21 +244,71 @@ pub fn readln_special<T: AsRef<Path>>(file_path: &T) -> Result<String> {
...
+
+// Closes all FDs other than 0 (STDIN), 1 (STDOUT) and 2 (STDERR)
+fn close_inherited_fds() -> Result<()> {
+    // The approach we take here is to firstly try to use the close_range syscall
+    // which is available on kernels > 5.9.
+    // We than fallback to using /proc/sef/fd to close open fds.
+    if close_fds_by_close_range().is_err() {
+        close_fds_by_reading_proc()?;
+    }
+    Ok(())
```
Comment (luminitavoicu) [inline src/jailer/src/main.rs:301]: nit:
```suggestion
    if close_fds_by_close_range().is_err() {
        close_fds_by_reading_proc()
    }
```

File: src/jailer/src/main.rs [hunk 4]
```diff
@@ -235,21 +244,71 @@ pub fn readln_special<T: AsRef<Path>>(file_path: &T) -> Result<String> {
...
         }
     }
+    Ok(())
+}
+
+// Closes all FDs other than 0 (STDIN), 1 (STDOUT) and 2 (STDERR)
+fn close_inherited_fds() -> Result<()> {
+    // The approach we take here is to firstly try to use the close_range syscall
+    // which is available on kernels > 5.9.
+    // We than fallback to using /proc/sef/fd to close open fds.
```
[the remark this answers is not in the document]
Comment (andreitraistaru) [reply src/jailer/src/main.rs:297]:
```suggestion
    // We then fallback to using /proc/self/fd to close open fds.
```

File: Cargo.lock [hunk 5]
```diff
@@ -681,6 +682,18 @@ dependencies = [
  "memoffset",
 ]
 
+[[package]]
+name = "nix"
+version = "0.26.2"
```
Comment (roypat) [inline Cargo.lock:687]: Mhh, the entry before this one is about nix 0.23.1 (transitive dependency). Can we do this with nix 0.23 so that we don't pull in the dependency twice??

**Review by dianpopa — COMMENTED** [review]
@lumivo @atc @roypat I also updated the changelog, can you take another look?
@roypat addressed your comment around the nix dependency

File: Cargo.lock (hunk 5 above)
Comment (roypat) [reply Cargo.lock:687]: Works for me to do that as a follow up then, no need to block this on it

**Review by roypat — APPROVED** [review]

File: src/jailer/src/main.rs (hunk 2 above)
Comment (luminitavoicu) [reply src/jailer/src/main.rs:259]: That makes sense. Let's keep it as is.

File: src/jailer/src/main.rs [hunk 6]
```diff
@@ -235,21 +244,70 @@ pub fn readln_special<T: AsRef<Path>>(file_path: &T) -> Result<String> {
...
         }
     }
+    Ok(())
+}
+
+// Closes all FDs other than 0 (STDIN), 1 (STDOUT) and 2 (STDERR)
+fn close_inherited_fds() -> Result<()> {
+    // The approach we take here is to firstly try to use the close_range syscall
+    // which is available on kernels > 5.9.
+    // We then fallback to using /proc/sef/fd to close open fds.
```
Comment (andreitraistaru) [inline src/jailer/src/main.rs:296]:
```suggestion
    // We then fallback to using /proc/self/fd to close open fds.
```

Comment (andreitraistaru) [reply src/jailer/src/main.rs:296]: looks good to me apart from this very small nit

**Review by andreitraistaru — APPROVED** [review]
