### PR TITLE
Removed sysconf dependency

### LINKED ISSUE #2187: Remove sysconf crate dependency
## Describe the bug

Given that we strive to keep the number of dependencies to a minimum, it seems that sysconf crate is an easy candidate as far as minimizing Firecracker dependencies. The `sysconf` crate is used to obtain the size of a page on the host with `sysconf::page::pagesize();` This dependency could be easily replaced with `libc::sysconf()`.

After issue is solved, check if Cargo.lock still contains "sysconf" as a dependency.

### PR DESCRIPTION
**Pull request by luminitavoicu**
Signed-off-by: Luminita Voicu <lumivo@amazon.com>

# Reason for This PR

In Firecracker the sysconf crate is only used for fetching the system's page size. In order to keep the dependencies list to a minimum, sysconf could be removed.
Fixes #2187 

## Description of Changes

Replaced sysconf's `pagesize()` with `libc::sysconf(libc::_SC_PAGESIZE)`.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

File: src/vmm/src/memory_snapshot.rs [hunk 1]
```diff
@@ -117,8 +118,11 @@ impl SnapshotMemory for GuestMemoryMmap {
         writer: &mut T,
         dirty_bitmap: &DirtyBitmap,
     ) -> std::result::Result<(), Error> {
-        let page_size = sysconf::page::pagesize();
         let mut writer_offset = 0;
+        let page_size = match unsafe { libc::sysconf(libc::_SC_PAGESIZE) } {
+            -1 => panic!("Failed to dump dirty pages: {}", errno::Error::last()),
```
Comment (sandreim) [inline src/vmm/src/memory_snapshot.rs:123]: I think we need to return an error here instead of a panic.

Comment (luminitavoicu) [reply src/vmm/src/memory_snapshot.rs:123]: I chose to panic here instead of throwing an error because this is the behavior of `sysconf::page::pagesize()`:

```
fn priv_pagesize() -> usize {
    // sysconf(_SC_PAGESIZE) is required by POSIX 1003.1: http://www.unix.com/man-page/posix/3p/sysconf/
    ::raw::sysconf(::raw::SysconfVariable::ScPagesize).expect("sysconf(_SC_PAGESIZE) failed, but _SC_PAGESIZE is required by POSIX 1003.1") as usize
}
```

 and also because `libc::sysconf` can only return error when the parameter is not an accepted one (which would never be the case here). 

However, it would make for a more consistent and elegant approach to raise an error here. I will change the behavior.

Comment (berciuliviu) [reply src/vmm/src/memory_snapshot.rs]: I've observed the same "panic" behaviour inside mmap.rs - line 79 - **enable_dirty_page_tracking**. I wonder if it is worth changing it there also to return an error? From my short investigation, I'd say we leave it like that, that since I believe will involve more complex changes, but it is worth taking it into consideration.

**Review by berciuliviu — COMMENTED** [review]
Looks good to me. Just remove the dot following commit title for the buildkite tests to pass.

File: src/vmm/src/memory_snapshot.rs [hunk 2]
```diff
@@ -117,8 +121,11 @@ impl SnapshotMemory for GuestMemoryMmap {
         writer: &mut T,
         dirty_bitmap: &DirtyBitmap,
     ) -> std::result::Result<(), Error> {
-        let page_size = sysconf::page::pagesize();
         let mut writer_offset = 0;
+        let page_size = match unsafe { libc::sysconf(libc::_SC_PAGESIZE) } {
```
Comment (dianpopa) [inline src/vmm/src/memory_snapshot.rs:125]: I suggest to write a function for this and use that in the unit tests, WDYT?

File: tests/integration_tests/build/test_coverage.py [hunk 3]
```diff
@@ -23,7 +23,7 @@
 # this contains the frequency while on AMD it does not.
 # Checkout the cpuid crate. In the future other
 # differences may appear.
-COVERAGE_DICT = {"Intel": 85.18, "AMD": 84.47, "ARM": 83.25}
+COVERAGE_DICT = {"Intel": 85.18, "AMD": 84.47, "ARM": 83.37}
```
Comment (dianpopa) [inline tests/integration_tests/build/test_coverage.py:26]: 💯

File: src/vmm/src/memory_snapshot.rs (hunk 1 above)
Comment (luminitavoicu) [reply src/vmm/src/memory_snapshot.rs]: We did take that into consideration at that time and decided it would be best to stick with the `panic` approach, because the vm-memory proxy uses errors imported from the upstream vm-memory crate.

File: src/vmm/src/memory_snapshot.rs (hunk 2 above)
Comment (luminitavoicu) [reply src/vmm/src/memory_snapshot.rs:125]: Good idea!

**Review by dianpopa — DISMISSED** [review]

File: src/vmm/src/memory_snapshot.rs [hunk 4]
```diff
@@ -200,18 +207,23 @@ impl SnapshotMemory for GuestMemoryMmap {
     }
 }
 
+fn get_page_size() -> i64 {
+    unsafe { libc::sysconf(libc::_SC_PAGESIZE) }
+}
```
Comment (acatangiu) [inline src/vmm/src/memory_snapshot.rs:212]: I would include _error parsing_ in this function instead of moving that to the caller:
```suggestion
fn get_page_size() -> Result<usize> {
    match unsafe { libc::sysconf(libc::_SC_PAGESIZE) } {
        -1 => Err(Error::PageSize(errno::Error::last())),
        ps => Ok(ps),
    }
}
```

**Review by dianpopa — DISMISSED** [review]

File: src/vmm/src/memory_snapshot.rs (hunk 4 above)
Comment (luminitavoicu) [reply src/vmm/src/memory_snapshot.rs]: Done

**Review by dianpopa — APPROVED** [review]

**Review by berciuliviu — APPROVED** [review]
