### PR TITLE
Aarch64 serial fix

### LINKED ISSUE #1147: Serial Console does not show login on aarch64
The serial console on aarch64 does not show the login prompt. It seems like it gets stuck before that. I am using the root filesystem, kernel image and boot arguments specified in [getting started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker) for aarch64.

[dmesg_aarch64.txt](https://github.com/firecracker-microvm/firecracker/files/3311395/dmesg_aarch64.txt)

### PR DESCRIPTION
**Pull request by sandreim**
Fixes #1147,  #1144

Description of changes:
- Added kernel configuration for aarch64 in resources folder (the previous configuration was missing CONFIG_SERIAL_OF_PLATFORM so the guest uart driver was not probing the device tree for ports)
- Changed serial IRQ from level to edge triggered (aarch64).
- Updated the device tree entry to use the clock node definition.
- Changed the early console settings to 8bit mmio.
- Rework serial device integration in VMM: no need to access the serial device object
- Implemented RawIOHandler trait + get_raw_io_device() mapping the RawIOHandler trait
- Implemented arch dependent get_serial_device()
- Move stdin_handle from LegacyDeviceManager to VMM.

Note: S3 update of kernel and rootfs images are also required. I'll update them after PR is merged.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acatangiu** [comment]
nit: We like to use the [50/72 rule](https://www.midori-global.com/blog/2018/04/02/git-50-72-rule) for our commit messages.

File: vmm/src/device_manager/mmio.rs [hunk 1]
```diff
@@ -81,6 +81,7 @@ pub struct MMIODeviceManager {
     irq: u32,
     last_irq: u32,
     id_to_dev_info: HashMap<(DeviceType, String), MMIODeviceInfo>,
+    pub stdio_serial: Option<Arc<Mutex<devices::legacy::Serial>>>,
```
Comment (acatangiu) [inline vmm/src/device_manager/mmio.rs]: nit: remove `pub` and add a getter method (this is not set outside its implementation so setter not required)

Comment (acatangiu) [reply vmm/src/device_manager/mmio.rs]: I think we should also mark this `#[cfg(target_arch = "aarch64")]`. Even if it's just an `Option` that will stay `None` on `x86_64`, it might be helpful for anyone looking at the definition of `MMIODeviceManager` to clearly see that the serial is a MMIO-device only on `aarch64`.

Comment (dianpopa) [reply vmm/src/device_manager/mmio.rs]: @sandreim I am not sure this was necessary.
There is a `get_device` function in this structure:
```
    /// Gets the the specified device.
    pub fn get_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<BusDevice>> {
```
that you could use. Something of the kind:
```
device_manager
                .get_device(DeviceType::Serial, "uart")
```
Doesn t this do the job?

File: vmm/src/lib.rs [hunk 2]
```diff
@@ -1551,10 +1551,24 @@ impl Vmm {
                             self.epoll_context.disable_stdin_event();
                         }
                         Ok(count) => {
+                            // There are 2 serial devices instantiated at this point:
+                            // One lives in LegacyDeviceManager and the other in MMIODeviceManager
+                            // Use the one that is actually plugged in the Guest.
+                            #[cfg(target_arch = "aarch64")]
+                            let serial = self
```
Comment (dianpopa) [inline vmm/src/lib.rs]: What I would do here for more elegance would be this:
Have a helper function (maybe `self.get_stdio_serial()`) that has two implementations, one for x86_64 and one for aarch64. See the example of 
`    fn attach_legacy_devices(&mut self) -> std::result::Result<(), StartMicrovmError> {
`
Additionally, if you decide to use the `get_device` function from the `MMIODeviceManager`, this will become `self.mmio_device_manager.get_device(DeviceType::Serial, "uart")`.

File: arch/src/aarch64/fdt.rs [hunk 3]
```diff
@@ -450,12 +450,13 @@ fn create_serial_node<T: DeviceInfoForFDT + Clone + Debug>(
...
 ) -> Result<()> {
     let serial_reg_prop = generate_prop64(&[dev_info.addr(), dev_info.length()]);
-    let irq = generate_prop32(&[GIC_FDT_IRQ_TYPE_SPI, dev_info.irq(), IRQ_TYPE_LEVEL_HI]);
+    let irq = generate_prop32(&[GIC_FDT_IRQ_TYPE_SPI, dev_info.irq(), IRQ_TYPE_EDGE_RISING]);
 
     append_begin_node(fdt, &format!("uart@{:x}", dev_info.addr()))?;
     append_property_string(fdt, "compatible", "ns16550a")?;
     append_property(fdt, "reg", &serial_reg_prop)?;
-    append_property_u32(fdt, "clock-frequency", 3686400)?;
+    append_property_u32(fdt, "clocks", CLOCK_PHANDLE)?;
```
Comment (dianpopa) [inline arch/src/aarch64/fdt.rs]: Seems like we also hit [this one](https://github.com/qemu/qemu/blob/e65472c7bc413d79faa61eb1d05c540b03945894/hw/arm/virt.c#L223) :(

File: vmm/src/lib.rs (hunk 2 above)
Comment (sandreim) [reply vmm/src/lib.rs]: >     * PortIODeviceManager should be compiled out for aarch64 (as a consequence of this, you could also need to compile out some more things, like the i8042 usages). I would do a separate commit for this.
> 
>     * Remove the `Option` around the `MMIODeviceManager`, this will also benefit the x86_64 logic since we are always calling `self.attach_virtio_devices()?;` at `start_microvm` no matter what.

I will perform the rename, but outcompiling this on aarch64 will backfire by lots of
`#[cfg(target_arch = "x86_64")]` in different parts of the codebase. 
Also removing the Option depends on also initializing guest memory before instantiating the PortIODeviceManager generating even more code changes.
I think this should be done as a separate refactoring PR with a clear design defined and agreed by all.

File: vmm/src/lib.rs [hunk 4]
```diff
@@ -1143,6 +1148,23 @@ impl Vmm {
...
     }
 
+    #[cfg(target_arch = "x86_64")]
+    fn get_serial_device(&self) -> Option<Arc<Mutex<RawIOHandler>>> {
+        Some(self.legacy_device_manager.stdio_serial.clone())
+    }
+
+    #[cfg(target_arch = "aarch64")]
+    fn get_serial_device(&self) -> Option<Arc<&Mutex<RawIOHandler>>> {
+        let raw_io_device = self
```
Comment (dianpopa) [inline vmm/src/lib.rs]: This function can be rewritten to:

```
    #[cfg(target_arch = "aarch64")]
    fn get_serial_device(&self) -> Option<&Arc<Mutex<RawIOHandler>>> {
        self
            .mmio_device_manager
            .as_ref()
            .unwrap()
            .get_raw_io_device(DeviceType::Serial, "uart")
    }
```
if you change its return result inside the `mmiodevicemanager`.

File: vmm/src/lib.rs [hunk 5]
```diff
@@ -1446,6 +1468,12 @@ impl Vmm {
             self.attach_legacy_devices()?;
         }
 
+        // set raw mode for stdin
```
Comment (dianpopa) [inline vmm/src/lib.rs]: nit: Upper case and full stop in comment for consistency with other comments.

File: vmm/src/device_manager/mmio.rs [hunk 6]
```diff
@@ -180,18 +182,25 @@ impl MMIODeviceManager {
...
+
         vm.register_irqfd(com_evt.as_raw_fd(), self.irq)
             .map_err(Error::RegisterIrqFd)?;
 
         self.bus
-            .insert(Arc::new(Mutex::new(device)), self.mmio_base, MMIO_LEN)
+            .insert(bus_device, self.mmio_base, MMIO_LEN)
             .map_err(|err| Error::BusError(err))?;
 
+        // register the RawIOHandler trait
```
Comment (dianpopa) [inline vmm/src/device_manager/mmio.rs]: nit: Upper case and full stop in comment.

File: vmm/src/device_manager/mmio.rs [hunk 7]
```diff
@@ -266,6 +275,21 @@ impl MMIODeviceManager {
         None
     }
 
+    #[allow(dead_code)]
+    pub fn get_raw_io_device(
+        &self,
+        device_type: DeviceType,
+        device_id: &str,
+    ) -> Option<&Mutex<RawIOHandler>> {
```
Comment (dianpopa) [inline vmm/src/device_manager/mmio.rs]: Why not?
```suggestion
    ) -> Option<&Arc<Mutex<RawIOHandler>>> {
```

Comment (sandreim) [reply vmm/src/device_manager/mmio.rs]: Ok!

File: devices/src/bus.rs [hunk 8]
```diff
@@ -29,6 +30,18 @@ pub trait BusDevice: AsAny + Send {
     fn interrupt(&self, irq_mask: u32) {}
 }
 
+/// Trait for devices that handle raw non-blocking I/O requests.
```
Comment (acatangiu) [inline devices/src/bus.rs]: nit: typo in commit "Rework serial device integration in VMM": s/`implmenet`/`implement`

Same commit message says:
> Rename LegacyDeviceManager to PortIODeviceManager

But the renaming has been done in the previous commit.

File: vmm/src/lib.rs [hunk 9]
```diff
@@ -1125,6 +1130,19 @@ impl Vmm {
...
+    fn get_serial_device(&self) -> Option<Arc<Mutex<RawIOHandler>>> {
+        Some(self.legacy_device_manager.stdio_serial.clone())
+    }
+
+    #[cfg(target_arch = "aarch64")]
+    fn get_serial_device(&self) -> Option<&Arc<Mutex<RawIOHandler>>> {
+        self.mmio_device_manager
+            .as_ref()
+            .unwrap()
+            .get_raw_io_device(DeviceType::Serial, "uart")
```
Comment (acatangiu) [inline vmm/src/lib.rs]: I don't personally like that we're building a "uart" `String` object that we then use in a hashmap search for each `Serial` input/output.

File: devices/src/bus.rs (hunk 8 above)
Comment (sandreim) [reply devices/src/bus.rs]: I'll move this commit message to where it belongs.

File: vmm/src/device_manager/mmio.rs [hunk 10]
```diff
@@ -266,6 +276,12 @@ impl MMIODeviceManager {
         None
     }
 
+    #[allow(dead_code)]
```
Comment (acatangiu) [inline vmm/src/device_manager/mmio.rs]: nit: I'd make this into:
```suggestion
    // Currently only used on 'aarch64'.
    #[cfg(target_arch = "aarch64")]
```
since it's not actually dead code.

File: vmm/src/lib.rs [hunk 11]
```diff
@@ -761,7 +765,7 @@ struct Vmm {
 
     // Guest VM devices.
     mmio_device_manager: Option<MMIODeviceManager>,
-    legacy_device_manager: LegacyDeviceManager,
+    legacy_device_manager: PortIODeviceManager,
```
Comment (acatangiu) [inline vmm/src/lib.rs]: Why not also change the variable name to smth like `portio_dev_manager`?
