### PR TITLE
Send transport_reset event on vsock snapshot create path

### LINKED ISSUE #2218: [Bug] Vsock device can break if snapshotted while doing traffic
## Bug description

Firecracker snapshots do not capture any inflight network or vsock (through the linux unix domain socket backend) traffic that has left or not yet entered Firecracker.

The above, coupled with the fact that Vsock control protocol is not resilient to vsock packet loss leads to Vsock device breakage when doing a snapshot while there are active Vsock connections.

## Possible fix

A clean way to support this would be to force a `virtio reset` on the vsock device on loading from snapshot.

## Workaround/Mitigation

Close all active Vsock connections prior to snapshotting the VM.

### PR DESCRIPTION
**Pull request by berciuliviu**
Fixes #2218 .

Signed-off-by: berciuliviu <lberciu@amazon.com>

# Reason for This PR

With this PR, we want to send the VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event to the
vsock driver when we create a snapshot. The event is sent only if the device is active.

## Description of Changes

Send VIRTIO_VSOCK_EVENT_TRANSPORT_RESET by filling a descriptor in the
event queue and signaling an interrupt event to the driver.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

**Review by luminitavoicu — COMMENTED** [review]
This needs an integration test

File: src/devices/src/virtio/vsock/device.rs [hunk 1]
```diff
@@ -213,6 +215,32 @@ where
...
+    // connections and the guest_cid configuration field is fetched again. Existing listen sockets remain
+    // but their CID is updated to reflect the current guest_cid.
+    pub fn send_transport_reset_event(&mut self) -> result::Result<(), DeviceError> {
+        let mem = match self.device_state {
+            DeviceState::Activated(ref mem) => mem,
+            // This should never happen, it's been already validated in the caller function.
+            DeviceState::Inactive => unreachable!(),
+        };
+
+        if let Some(head) = self.queues[EVQ_INDEX].pop(mem) {
```
Comment (sandreim) [inline src/devices/src/virtio/vsock/device.rs:229]: I think we also need to account for the situation when there are no available buffers.

Something like:
```
        let head_desc =self.queues[EVQ_INDEX].pop(mem).ok_or_else(|| {
            IncrementSomeMetric();
            SomeError::EmptyQueue
        })?;
```

**Review by sandreim — COMMENTED** [review]
Looks good! Some more areas to cover in this PR:
- unit tests 
- integration test
- changelog update

**Comment by berciuliviu** [comment]
> Looks good! Some more areas to cover in this PR:
> 
> * unit tests
> * integration test
> * changelog update

If I understand well, a testing scenario I consider would be: create a snapshot with a vsock device that has active connections and, after restoring from snapshot, verify that the connections are properly closed. Please correct me if I'm wrong. Do you still think we should have both unit and integration tests, or just one (such as integration) would suffice?

File: src/devices/src/virtio/vsock/persist.rs [hunk 2]
```diff
@@ -120,6 +120,11 @@ where
         } else {
             DeviceState::Inactive
         };
+
+        if state.virtio_state.activated {
+            vsock.send_transport_reset_event().unwrap();
```
Comment (luminitavoicu) [inline src/devices/src/virtio/vsock/persist.rs:125]: We should handle/propagate the possible errors here, instead of just using `unwrap()`.

File: src/devices/src/virtio/vsock/device.rs [hunk 3]
```diff
@@ -213,6 +215,32 @@ where
...
+            mem.write_obj::<u32>(VIRTIO_VSOCK_EVENT_TRANSPORT_RESET, head.addr)
+                .unwrap();
```
Comment (luminitavoicu) [inline src/devices/src/virtio/vsock/device.rs:231]: It's not safe to `unwrap()` here. Instead, we should handle the error:

```suggestion
             if let Err(e) =
                        mem.write_obj::<u32>(VIRTIO_VSOCK_EVENT_TRANSPORT_RESET, head.addr)
                    {
                        error!("Failed to write virtio vsock reset event: {:?}", e)
                    }   
```

**Comment by luminitavoicu** [comment]
Documentation on [vsock device limitations during snapshots](https://github.com/firecracker-microvm/firecracker/blob/main/docs/snapshotting/snapshot-support.md#vsock-device-limitations) needs to be updated, as well.

**Comment by berciuliviu** [comment]
@luminitavoicu @sandreim PTAL!

File: tests/integration_tests/functional/test_vsock.py [hunk 4]
```diff
@@ -179,3 +181,106 @@ def test_vsock_epipe(
...
+    # Guest-initiated connections (echo workers) will use this blob.
+    conn = SSHConnection(test_vm.ssh_config)
+    cmd = "mkdir -p /tmp/vsock"
+    cmd += " && mount -t tmpfs tmpfs -o size={} /tmp/vsock".format(
+        BLOB_SIZE + 1024*1024
+    )
+    ecode, _, _ = conn.execute_command(cmd)
+    assert ecode == 0
+
+    # Copy `vsock_helper`***9and the random blob to the guest.
```
Comment (sandreim) [inline tests/integration_tests/functional/test_vsock.py:232]: Typo ?

File: tests/integration_tests/functional/test_vsock.py [hunk 5]
```diff
@@ -179,3 +181,106 @@ def test_vsock_epipe(
...
+        test_fc_session_root_path
+):
+    """
+    Vsock transport reset test.
+
+    Steps:
+    1. Start echo server on the guest
+    2. Start host workers that ping-pong data between guest and host,
+    without closing any of them
+    3. Pause VM -> Create snapshot -> Resume VM
```
Comment (sandreim) [inline tests/integration_tests/functional/test_vsock.py:199]: We should also test the scenario when a VM is created with LoadSnapshot.

File: tests/integration_tests/performance/test_versioned_serialization_benchmark.py [hunk 6]
```diff
@@ -27,7 +27,7 @@
                 "delta": 0.025  # milliseconds
             },
             "crc": {
-                "target": 0.213,  # milliseconds
+                "target": 0.207,  # milliseconds
```
Comment (sandreim) [inline tests/integration_tests/performance/test_versioned_serialization_benchmark.py:30]: This doesn't seem to be related to this PR.

File: src/vmm/src/device_manager/persist.rs [hunk 7]
```diff
@@ -226,14 +226,22 @@ impl<'a> Persist<'a> for MMIODeviceManager {
...
+
                     let vsock_state = VsockState {
                         backend: vsock.backend().save(),
                         frontend: vsock.save(),
                     };
+
+                    // Send Transport event to reset connections if device
+                    // is activated.
+                    if vsock.is_activated() {
+                        vsock.send_transport_reset_event().unwrap();
```
Comment (sandreim) [inline src/vmm/src/device_manager/persist.rs:242]: I would avoid unwrap() here and generally as a means of reporting errors to the user. We need to either report the error up the stack, write it in the log or exiting gracefully. It depends on how bad it is. 

Either move this call outside of the Persist trait impl or refactor a bit so it allows error reporting on save().

File: src/logger/src/metrics.rs [hunk 8]
```diff
@@ -730,6 +730,8 @@ pub struct VsockDeviceMetrics {
     pub tx_queue_event_fails: SharedIncMetric,
     /// Number of times when handling event queue events on a vsock device failed.
     pub ev_queue_event_fails: SharedIncMetric,
+    /// No available buffer for the vsock event queue.
```
Comment (sandreim) [inline src/logger/src/metrics.rs:733]: This is a change worthy of changelog updates.

File: docs/snapshotting/snapshot-support.md [hunk 9]
```diff
@@ -532,8 +532,8 @@ Firecracker.
 to vsock packet loss, leads to Vsock device breakage when doing a snapshot while
 there are active Vsock connections.
 
-   _**Workaround**_: Close all active Vsock connections prior to snapshotting
-   the VM.
+   _**Workaround**_: All active Vsock connections prior to snapshotting
+   the VM are forcibly closed by sending a specific event called VIRTIO_VSOCK_EVENT_TRANSPORT_RESET.
```
Comment (sandreim) [inline docs/snapshotting/snapshot-support.md:536]: We need to also include some details for the users to clearly understand how they should build their vsock apps wrt snapshots.

File: tests/integration_tests/functional/test_vsock.py (hunk 4 above)
Comment (berciuliviu) [reply tests/integration_tests/functional/test_vsock.py:232]: Yes

File: tests/integration_tests/functional/test_vsock.py (hunk 5 above)
Comment (berciuliviu) [reply tests/integration_tests/functional/test_vsock.py:199]: Will do.

File: tests/integration_tests/build/test_coverage.py [hunk 10]
```diff
@@ -24,7 +24,8 @@
 # this contains the frequency while on AMD it does not.
 # Checkout the cpuid crate. In the future other
 # differences may appear.
-COVERAGE_DICT = {"Intel": 85.10, "AMD": 84.52, "ARM": 83.35}
+
```
Comment (luminitavoicu) [inline tests/integration_tests/build/test_coverage.py:27]: I assume this is not intentional.

File: docs/snapshotting/snapshot-support.md [hunk 11]
```diff
@@ -532,8 +532,15 @@ Firecracker.
 to vsock packet loss, leads to Vsock device breakage when doing a snapshot while
 there are active Vsock connections.
 
-   _**Workaround**_: Close all active Vsock connections prior to snapshotting
-   the VM.
+   As a solution to the above issue, active Vsock connections prior to
+snapshotting the VM are forcibly closed by sending a specific event called
+VIRTIO_VSOCK_EVENT_TRANSPORT_RESET. The event is sent on `SnapshotCreate`.
+On `SnapshotResume`, the vsock driver will close all existing connections.
```
[the remark this answers is not in the document]
Comment (berciuliviu) [reply docs/snapshotting/snapshot-support.md:538]: I wanted to specify here that, while the event is sent on SnapshotCreate, the connections will be closed when the VM is resumed, as at that point the VM will be functional again.

File: docs/snapshotting/snapshot-support.md [hunk 12]
```diff
@@ -532,8 +532,15 @@ Firecracker.
...
+Listen sockets still remain active. Users wanting to build vsock applications that
+use the snapshot capability have to take this into consideration. More details
+about this event can be found in the official Virtio document
+ [here](https://docs.oasis-open.org/virtio/virtio/v1.1/virtio-v1.1.pdf),
+ section 5.10.6.6 Device Events.
```
[the remark this answers is not in the document]
Comment (berciuliviu) [reply docs/snapshotting/snapshot-support.md:543]: Agree

File: docs/snapshotting/snapshot-support.md [hunk 13]
```diff
@@ -532,8 +532,19 @@ Firecracker.
 to vsock packet loss, leads to Vsock device breakage when doing a snapshot while
 there are active Vsock connections.
 
-   _**Workaround**_: Close all active Vsock connections prior to snapshotting
-   the VM.
+   As a solution to the above issue, active Vsock connections prior to
+snapshotting the VM are forcibly closed by sending a specific event called
+VIRTIO_VSOCK_EVENT_TRANSPORT_RESET. The event is sent on `SnapshotCreate`.
+On `SnapshotResume`, when the VM will become active again,
+the vsock driver will close all existing connections.
```
Comment (luminitavoicu) [inline docs/snapshotting/snapshot-support.md:539]: nit: let's stay consistent and use present time here. It sounds better IMHO.

File: docs/snapshotting/snapshot-support.md [hunk 14]
```diff
@@ -532,8 +532,19 @@ Firecracker.
...
+Listen sockets still remain active. Users wanting to build vsock applications that
+use the snapshot capability have to take this into consideration. More details
+about this event can be found in the official Virtio document
+ [here](https://docs.oasis-open.org/virtio/virtio/v1.1/virtio-v1.1.pdf),
+ section 5.10.6.6 Device Events.
```
Comment (luminitavoicu) [inline docs/snapshotting/snapshot-support.md:544]: super nit:
```suggestion
[here](https://docs.oasis-open.org/virtio/virtio/v1.1/virtio-v1.1.pdf),
section 5.10.6.6 Device Events.
```

File: docs/snapshotting/snapshot-support.md [hunk 15]
```diff
@@ -532,8 +532,19 @@ Firecracker.
...
+
+   Firecracker will handle this, thus the customers are no longer
+   responsible with closing active connections.
```
Comment (luminitavoicu) [inline docs/snapshotting/snapshot-support.md:547]: super nit: I think present time works better here, as well.
```suggestion
   Firecracker handles sending the `reset` event to the vsock driver,
thus the customers are no longer responsible for closing active connections.
```

**Review by luminitavoicu — COMMENTED** [review]
This looks good. I only have a couple of nits.

File: src/devices/src/virtio/queue.rs [hunk 16]
```diff
@@ -31,6 +31,8 @@ pub enum QueueError {
     DescIndexOutOfBounds(u16),
     /// Attempted an invalid write into the used ring.
     UsedRing(GuestMemoryError),
+    /// Empty queue
+    EmptyQueue,
```
Comment (sandreim) [inline src/devices/src/virtio/queue.rs:35]: This change defines a specific error at the generic virtio queue level. This clearly breaks modularization and separation of concerns as an empty queue is not a concern for the generic code. 

Ideally we want to be in a position to easily jump to this implmentation: https://github.com/rust-vmm/vm-virtio/blob/master/src/queue.rs/

**Comment by berciuliviu** [comment]
All comments addressed. @sandreim @luminitavoicu PTAL!

File: src/devices/src/virtio/vsock/mod.rs [hunk 17]
```diff
@@ -120,6 +120,8 @@ pub enum VsockError {
     /// Invalid virtio configuration.
     VirtioState(VirtioStateError),
     VsockUdsBackend(VsockUnixBackendError),
+    /// Empty queue
+    EmptyQueue,
```
Comment (luminitavoicu) [inline src/devices/src/virtio/vsock/mod.rs:124]: nit: ideally, we want to have `enum` variants in alphabetical order, to better find and navigate.

**Review by luminitavoicu — DISMISSED** [review]
Looks good!

**Review by luminitavoicu — APPROVED** [review]

**Review by sandreim — APPROVED** [review]
Looks great!
