### PR TITLE
Fix intermittent fail on AMD when getting cpu count

### LINKED ISSUE #2216: [Bug] SIGILL handler not called when running with kcov on arm64
## Describe the bug

While investigating why this test fails when running coverage test for arm64, I came to the conclusion that SIGILL handler does not get called at all. Investigate why this happens.

## To Reproduce
```
./tools/devtool shell -p
cd src/vmm
RUSTFLAGS="-C link-arg=-lgcc -C link-arg=-lfdt " cargo kcov --target aarch64-unknown-linux-musl

```

### PR DESCRIPTION
**Pull request by dianpopa**
# Reason for This PR

We have been dealing with intermittent fails for `vmm::signal_handler::test_signal_handler` on AMD.
This happens in the cpu_count() function due. We are computing the number of cpus by getting the affinity mask of current process and then going through CPU_SETSIZE to count the number of cpus that hit the mask. 
Problem is that `libc:musl` has a maximum of CPU_SETSIZE equal 128 and  on AMD the maximum number of CPUS with SMT enabled is 192.

Fixes #2216 

## Description of Changes

The cpu_count was used as an trick for detecting whether or not the unit tests are run under `cargo test` or `cargo kcov` since cargo kcov would make it seem that there is only one CPU online.

We remove this workaround and introduce a environment variable CARGO_WRAPPER that can tell us what is the wrapper currently run by cargo.

While implementing the solution, also found the reason why this happens: https://github.com/firecracker-microvm/firecracker/issues/2216. Comment in code.

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The issue which led to this PR has a clear conclusion.
- [ ] This PR follows the solution outlined in the related issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes follow the [Runbook for Firecracker API changes][2].
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

File: src/vmm/src/signal_handler.rs [hunk 1]
```diff
@@ -172,37 +172,15 @@ pub fn register_signal_handlers() -> utils::errno::Result<()> {
...
-            if unsafe { libc::CPU_ISSET(i, &cpuset) } {
-                num += 1;
-            }
-        }
-        num
-    }
-
     #[test]
     fn test_signal_handler() {
+        let run_with_kcov = env::var("CARGO_WRAPPER").is_ok();
```
Comment (bchalios) [inline src/vmm/src/signal_handler.rs:183]: nit: Maybe explicitly check for "kcov", just in case we need to check against other wrappers in the future

File: src/vmm/src/signal_handler.rs [hunk 2]
```diff
@@ -258,27 +236,26 @@ mod tests {
...
-            assert!(METRICS.seccomp.num_faults.fetch() >= 1);
-        }
+        // SIGSYS, which is raised whenever a bad syscall is caught will be intercepted by kcov on x86_64
+        // and thus not reach Firecracker:
+        // https://github.com/SimonKagstrom/kcov/blob/a8b60c43fb33f56553a2bb20633e3b59a08abae1/src/engines/ptrace.cc#L187
+        // So, we are not checking for the `num_faults` metrics which gets incremented on each bad syscall
+        // if we run with kcov and we are on x86_64.
+        assert!(
+            METRICS.seccomp.num_faults.fetch()
+                >= (!run_with_kcov || !cfg!(target_arch = "x86_64")) as usize
```
Comment (bchalios) [inline src/vmm/src/signal_handler.rs:246]: Do we actually need to check for the `target_arch` here? There wasn't there in the original code.

**Review by luminitavoicu — COMMENTED** [review]
Apart from the already existing comments, looks good to me!

File: src/vmm/src/signal_handler.rs (hunk 1 above)
Comment (dianpopa) [reply src/vmm/src/signal_handler.rs]: Done.

File: src/vmm/src/signal_handler.rs (hunk 2 above)
Comment (dianpopa) [reply src/vmm/src/signal_handler.rs]: Yes, so I wanted to be really strict about this in order to reflect on the reason behind why this happens. The num_faults is 0 only on x86_64 since kcov will intercept the SIGSYS while on ARM, SIGILL is the one intercepted which motivates the next change.
The explanation is here: https://github.com/SimonKagstrom/kcov/blob/a8b60c43fb33f56553a2bb20633e3b59a08abae1/src/engines/ptrace.cc#L187

**Review by bchalios — APPROVED** [review]
LGTM

File: src/vmm/src/signal_handler.rs [hunk 3]
```diff
@@ -258,27 +236,26 @@ mod tests {
...
         assert!(METRICS.signals.sigxfsz.fetch() >= 1);
         assert!(METRICS.signals.sigxcpu.fetch() >= 1);
         assert!(METRICS.signals.sigpipe.count() >= 1);
         assert!(METRICS.signals.sighup.fetch() >= 1);
-        // Workaround to GitHub issue 2216.
-        #[cfg(not(target_arch = "aarch64"))]
-        assert!(METRICS.signals.sigill.fetch() >= 1);
+        assert!(
+            METRICS.signals.sigill.fetch()
+                >= (!run_with_kcov || !cfg!(target_arch = "aarch64")) as usize
```
[the remark this answers is not in the document]
Comment (bchalios) [reply src/vmm/src/signal_handler.rs]: ok, it makes sense! thanks!

**Review by luminitavoicu — APPROVED** [review]
