### PR TITLE
CI needed adjustments for aarch64

### LINKED ISSUE #758: Get the processor’s time-stamp counter in aarch64
We use `std::arch::x86_64::_rdtsc()`. Implement equivalent for `aarch64` for reading the current value of the processor’s time-stamp counter.

### LINKED ISSUE #955: Add backtrace for arm builds
PR #948 is disabling backtrace for arm builds because it is a hustle to cross compile musl-gcc for arm. Cross-compiling Firecracker with the `aarch64-unknown-linux-musl` target is the only good way we have at the moment to test the arm build as part of our CI.

When we have a production ready support for arm, we should make sure to re-enable it.

### LINKED ISSUE #1078: Remove arm cross compilation test from CI
Once the CI is sucessfully run on arm instances, we need to remove any cross compilation tests taking place right now.
This also implies removing any dependencies from Dockerfile and docker image/tag (i.e libfdt).

### LINKED ISSUE #1116: Investigate failure upon sending PATCH request on drive on aarch64
Currently the `test_patch_drive.py` is failing on aarch64. Investigate this.

### PR DESCRIPTION
**Pull request by dianpopa**
Issue #, if available:
* Fixes #1116 
* Fixes #1078 
* Fixes #955 
* Fixes #758 

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: arch/src/aarch64/fdt.rs [hunk 1]
```diff
@@ -484,7 +485,19 @@ fn create_devices_node<T: DeviceInfoForFDT + Clone + Debug>(
     fdt: &mut Vec<u8>,
     dev_info: &HashMap<(DeviceType, String), T>,
 ) -> Result<()> {
-    for ((device_type, _), info) in &*dev_info {
+    // We are trying to detect the root block device. We know
```
Comment (serban300) [inline arch/src/aarch64/fdt.rs]: This seems like a brute force approach. Is there any other simpler way to do this ?

File: tests/integration_tests/build/test_unittests.py [hunk 2]
```diff
@@ -8,38 +8,45 @@
...
-            os.path.join(test_session_root_path, CARGO_UNITTEST_REL_PATH),
-        ),
-        shell=True,
-        check=True
-    )
+@pytest.mark.parametrize(
+    "features, target",
+    itertools.product(FEATURES, TARGETS)
+)
+def test_unittests(test_session_root_path, features, target):
```
Comment (andreeaflorescu) [inline tests/integration_tests/build/test_unittests.py]: There is no need to have `features` as a cartesian product. This can be optimized as follows:
- paramterize only based on targets (musl vs gnu)
- in the test body check if the platform is x86_64 and if that's the case add an extra parameter to cargo test `--all-features`.

This would result in running the following tests:
- [x86_64] cargo test --all-features --target unknow-gnu -> we run the vsock tests as well
- [x86_64] cargo test --all-features --target unkown-musl -> we run the vsock tests as well
- [aarch_64] cargo test --target unknow-gnu -> only the default tests, no vsock
- [aarch_64] cargo test --target unknown-musl -> only the default tests, no vsock

Running `cargo test --features vsock` includes the tests being run only with `cargo test` so we are basically running all default tests twice.

File: tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs [hunk 3]
```diff
@@ -20,14 +20,18 @@ pub fn jailer_required_rules() -> Vec<SyscallRuleSet> {
         allow_syscall(libc::SYS_rt_sigprocmask),
         allow_syscall(libc::SYS_rt_sigaction),
         allow_syscall(libc::SYS_execve),
-#[cfg(target_arch = "x86_64")]
+        #[cfg(target_arch = "x86_64")]
         allow_syscall(libc::SYS_mmap),
-#[cfg(target_arch = "x86_64")]
+        #[cfg(target_arch = "aarch64")]
+        // See this issue for why we are doing it this way on arch64:
+        // https://github.com/rust-lang/libc/issues/1348.
```
Comment (andreeaflorescu) [inline tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs]: Can we open an issue about this in firecracker-microvm and submit a PR to libc? It looks like an easy fix and we wouldn't need to have hardcoded values in the code.

In the meantime, please specify in the comment what syscall is this one that you're whitelisting.

File: vmm/src/device_manager/mmio.rs [hunk 4]
```diff
@@ -87,12 +87,15 @@ impl MMIODeviceManager {
     /// Create a new DeviceManager handling mmio devices (virtio net, block).
     pub fn new(
         guest_mem: GuestMemory,
-        mmio_base: u64,
+        mmio_base: &mut u64,
```
Comment (andreeaflorescu) [inline vmm/src/device_manager/mmio.rs]: This seems like a change worth mentioning in the commit message as well.

File: devices/src/legacy/rtc_pl031.rs [hunk 5]
```diff
@@ -265,7 +265,7 @@ mod tests {
         assert_eq!(no_errors_after - no_errors_before, 1);
         // However, reading from the AMBA_ID_LOW should succeed upon read.
 
-        let mut data = [0; 8];
+        let mut data = [0; 4];
```
Comment (andreeaflorescu) [inline devices/src/legacy/rtc_pl031.rs]: Please add some more details to the commit message so we know why we made it 4 instead of 8.

File: vmm/src/default_syscalls/aarch64.rs [hunk 6]
```diff
@@ -69,7 +68,6 @@ pub fn default_filter() -> Result<SeccompFilter, Error> {
             ),
             allow_syscall(SYS_mmap),
             allow_syscall(libc::SYS_munmap),
-            #[cfg(target_env = "musl")]
```
Comment (andreeaflorescu) [inline vmm/src/default_syscalls/aarch64.rs]: On x86_64 SYS_openat was only used with musl while SYS_open was used with glibc. Is this different on aarch64?

File: api_server/src/request/mod.rs [hunk 7]
```diff
@@ -294,13 +294,15 @@ mod tests {
...
         check_error_response(vmm_resp, StatusCode::InternalServerError);
         #[cfg(target_arch = "x86_64")]
-        let vmm_resp = VmmActionError::StartMicrovm(
-            ErrorKind::Internal,
-            StartMicrovmError::ConfigureSystem(arch::Error::X86_64Setup(
-                arch::x86_64::Error::ZeroPagePastRamEnd,
-            )),
-        );
-        check_error_response(vmm_resp, StatusCode::InternalServerError);
+        {
```
[the remark this answers is not in the document]
Comment (andreeaflorescu) [reply api_server/src/request/mod.rs]: We can also look for other code paths that return the status code `InternalServerError`. It doesn't necessarily need to come from `configure_system`.

File: .cargo/config [hunk 8]
```diff
@@ -1,11 +1,10 @@
 [build]
 target = "x86_64-unknown-linux-musl"
 
-[target.aarch64-unknown-linux-musl]
+[target.'cfg(any(target_arch="arm", target_arch="aarch64"))']
```
[the remark this answers is not in the document]
Comment (andreeaflorescu) [reply .cargo/config]: I was asking if the configuration is needed for gnu builds as well.

File: arch/src/aarch64/fdt.rs (hunk 1 above)
Comment (serban300) [reply arch/src/aarch64/fdt.rs]: Ok, probably it wouldn't be worth it sending the id of the root block device as a parameter, but I would change the approach a little bit:

- iterate thorough the entire hashmap and remember the id with the lowest address. 
- get the device_info for the rootfs id and append it to the FDT first
- inside the for loop check if the current device type == TYPE_BLOCK && current id == rootfs_id . If it is, skip the entry

I don't think it would require more lines of code and it would help avoiding all the cloning.

File: tests/integration_tests/build/test_unittests.py [hunk 9]
```diff
@@ -8,38 +8,42 @@
...
-    """Run unit and doc tests from all crates using default target."""
-    run(
-        'CARGO_TARGET_DIR={} RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test '
-        '--all --no-fail-fast'.format(
-            os.path.join(test_session_root_path, CARGO_UNITTEST_REL_PATH),
-        ),
-        shell=True,
-        check=True
-    )
+    This will generate unit tests instances using the cartesian product of all
```
Comment (andreeaflorescu) [inline tests/integration_tests/build/test_unittests.py]: The comment needs to be updated as it generates tests only for different targets.

Comment (dianpopa) [reply tests/integration_tests/build/test_unittests.py]: Done, take a look.

File: arch/src/aarch64/fdt.rs (hunk 1 above)
Comment (dianpopa) [reply arch/src/aarch64/fdt.rs]: @serban300 thanks for the tips. They really helped. Take a look at how I changed the code. I got rid of all the clones but kept the sort since I though it was more elegant this way. Hope it is ok.

Comment (dianpopa) [reply arch/src/aarch64/fdt.rs]: Done, take a look.
