### PR TITLE
aarch64: remove m6g platform dependencies from unit tests

### LINKED ISSUE #2492: [Bug] Unit test aarch64 functionality through a mock fs for platform-agnostic reasons
# Describe the bug

Some of the aarch64 specific unit tests rely on checks that are m6g specific (i.e the FDT is checked against an [m6g specific FDT](https://github.com/firecracker-microvm/firecracker/blob/master/src/arch/src/aarch64/fdt.rs#L738)). This means that running the unit tests on another platform different than m6g will fail.

## Expected behaviour

The aarch64 unit tests are platform agnostic, meaning the unit tests can successfully run on any aarch64 system. Here we need to solve the issue of being able to create a mock fs and delete it once the test function terminates (successfully or not).

### PR DESCRIPTION
**Pull request by dianpopa**
# Reason for This PR

Fixes #2492 

## Description of Changes

- use a dummy cache topology in unit tests
- create a gicv2 equivalent fdt file
- regenerate the gicv3 saved fdt to contain the dummy cache topology

This PR enables succesful run of unit tests on any gicv2 and gicv3 enabled instance since it removes the m6g dependency introduced by validating against a m6g specific cache topology and a m6g specific fdt.
The PR can be tested on an a1.metal by forcing the [create_gic](https://github.com/firecracker-microvm/firecracker/blob/main/src/arch/src/aarch64/gic/mod.rs#L157) function to create a GICv2 device.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

File: src/arch/src/aarch64/cache_info.rs [hunk 1]
```diff
@@ -1,27 +1,43 @@
...
-#[derive(Clone)]
-pub(crate) struct CacheInfo {
+struct CacheEngine {
+    store: Box<dyn CacheStore>,
+}
+
+trait CacheStore: std::fmt::Debug {
+    fn get_by_key(&self, index: u8, file_name: &str) -> Result<String>;
+
+    fn as_any(&self) -> &dyn Any;
```
Comment (alindima) [inline src/arch/src/aarch64/cache_info.rs:34]: are the `as_any` and `as_mut_any` methods used anywhere?
I commented them and the code still compiles

Comment (serban300) [reply src/arch/src/aarch64/cache_info.rs:34]: It seems to be needed in tests to downcast the trait to an actual type. Anyway, we already have such a trait defined in [devices](https://github.com/firecracker-microvm/firecracker/blob/96d0ce9b97e7443125ccca9b89effe21720d7b15/src/devices/src/virtio/mod.rs#L72) . Can we move it to `utils` and reuse it here ?

File: src/arch/src/aarch64/cache_info.rs [hunk 2]
```diff
@@ -120,92 +167,80 @@ impl CacheType {
...
-                    .parse::<u8>()
-                    .map_err(|e| Error::InvalidCacheAttr("level".to_string(), e.to_string()))?;
-            }
-            Err(e) => {
-                // If we cannot read the cache level even for the first level of cache, we will
-                // stop processing anymore cache info and log an error.
-                warn!("Could not read cache level for index {}: {}", index, e);
-                return Err(Error::MissingCacheConfig);
-            }
+fn populate_cache_entry(index: u8, store: &dyn CacheStore) -> Result<CacheEntry> {
```
Comment (serban300) [inline src/arch/src/aarch64/cache_info.rs:170]: would it make sense to define this method as a constructor for `CacheEntry` ? `from_index()` maybe ?

File: src/arch/src/aarch64/cache_info.rs [hunk 3]
```diff
@@ -319,43 +351,56 @@ pub(crate) fn sysfs_read_caches(
...
+        }
+    }
+
+    fn insert_mock_entry(store: &mut MockCacheStore, key: String, val: String) {
+        store.dummy_fs.insert(key, val);
+    }
+
+    fn remove_mock_entry(store: &mut MockCacheStore, key: &str) {
+        store.dummy_fs.remove(key);
     }
```
Comment (serban300) [inline src/arch/src/aarch64/cache_info.rs:404]: Can we define this methods inside `MockCacheStore` ?

File: src/arch/src/aarch64/cache_info.rs [hunk 4]
```diff
@@ -1,27 +1,43 @@
...
+    MissingOptionalAttr(String, CacheEntry),
 }
 
 type Result<T> = result::Result<T, Error>;
 
-#[derive(Clone)]
-pub(crate) struct CacheInfo {
+struct CacheEngine {
+    store: Box<dyn CacheStore>,
+}
```
Comment (serban300) [inline src/arch/src/aarch64/cache_info.rs:29]: Do we need the inner store ? If we could implement a trait like `CacheStore` (probably renamed) directly on the cache engine, it would make the code simpler. We wouldn't need to use any `#[cfg(not(test))]` anymore, and also we wouldn't need `as_any`. In the actual implementation we would use the `HostCacheEngine` directly and in the tests we would use the `MockCacheEngine` directly.

File: src/arch/src/aarch64/cache_info.rs (hunk 1 above)
Comment (dianpopa) [reply src/arch/src/aarch64/cache_info.rs]: I rewrote the tests to get rid of the Any implementation.

File: src/arch/src/aarch64/cache_info.rs (hunk 2 above)
Comment (dianpopa) [reply src/arch/src/aarch64/cache_info.rs]: Done

**Comment by dianpopa** [comment]
@alindima @serban300 PTAL!

**Review by serban300 — APPROVED** [review]

**Review by alindima — APPROVED** [review]

**Review by serban300 — APPROVED** [review]

**Review by alindima — APPROVED** [review]
