### PR TITLE
rate-limiter: remove code-paths that divide by zero

### LINKED ISSUE #1918: Firecracker crashes when patching rate-limiter with zero refill time
Firecracker crashes when patching rate limiter with  refill time of size **zero**.

Example payload:
```bash
curl_patch '/network-interfaces/net1' <<EOF
{
  "iface_id": "net1",
  "tx_rate_limiter": {
    "bandwidth": {
      "size": 0,
      "refill_time": 0 
    }
  }
}
EOF
```

Results in Firecracker crash:
```bash
The API server received a Patch request on "/network-interfaces/net1" with body "{  \"iface_id\": \"net1\",  \"tx_rate_limiter\": {    \"bandwidth\": {      \"size\": 0,      \"refill_time\": 0     }  }}".
Firecracker panicked at 'attempt to divide by zero', src/rate_limiter/src/lib.rs:123:39
Shutting down VM after intercepting a bad syscall (79).
```

We should make sure to disallow the `divide by zero` path.

### PR DESCRIPTION
**Pull request by acatangiu**
## Reason for This PR

Fixes #1918 

## Description of Changes

TokenBucket constructor now validates input and provides 'None' result meaning disabled when its 'size' or 'refill_time' are zero.

Simplify and slightly optimize code by changing 'one_time_burst' from 'Option<u64>' to simple 'u64'. Value of zero is equivalent to 'None'.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.

### CODE REVIEW

**Comment by raduiliescu** [comment]
Should the checks be done at config time, or it doesn't apply?

**Comment by acatangiu** [comment]
> Should the checks be done at config time, or it doesn't apply?

RateLimiter constructor was using helper function `make_bucket` which did those checks and provided valid parameters to `TokenBucket`.

This PR removes the helper function and changes `TokenBucket` itself to validate input parameters, thus _removing_ the problem.

All paths (`initial config`, `patch`, `restore`) are now covered.

File: src/rate_limiter/src/lib.rs [hunk 1]
```diff
@@ -426,23 +428,17 @@ impl RateLimiter {
...
-        // as the token bucket config, the old config is left unchanged.
-
-        if let Some(b) = bytes {
-            self.bandwidth = Self::make_bucket(b.size, b.one_time_burst, b.refill_time);
-        }
-
-        if let Some(b) = ops {
-            self.ops = Self::make_bucket(b.size, b.one_time_burst, b.refill_time);
-        }
+    pub fn update_buckets(&mut self, bytes: BucketUpdate, ops: BucketUpdate) {
```
Comment (ioanachirca) [inline src/rate_limiter/src/lib.rs:424]: Nice!

**Comment by acatangiu** [comment]
You can ignore the AMD failure. It is a buildkite pipeline problem that @dianpopa is working on a fix for.
