### PR TITLE
Return error when setting CPU template on aarch64

### LINKED ISSUE #2165: [Bug] Return error if user wants to configure CPU templates for aarch64
## Describe the bug

Firecracker offers users the possibility of configuring the CPU features exposed by the guest by applying C3 and T2 templates. On aarch64, this functionality is not supported yet. However, trying to specify a cpu template through the API on aarch64 is possible even though it has no consequences.

## To Reproduce

` 1. Start Firecracker on an aarch64 via ./build/cargo_target/aarch64-unknown-linux-musl/debug/firecracker --api-sock /tmp/firecracker.socket.`
`2. Configure Firecracker via curl --unix-socket /tmp/firecracker.socket -i \
     -X PUT "http://localhost/machine-config" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -d "{ 
	    \"vcpu_count\": 1, 
	    \"mem_size_mib\": 32,
	    \"ht_enabled\": false,
	    \"cpu_template\": \"T2\"
         }"`

==> no error is returned.

## Expected behaviour

Error should be returned when user specifies CPU template on aarch64.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks
- [ ] Have you searched the Firecracker Issues database for similar problems?
- [ ] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by ahmedaabouzied**
## Reason for This PR

Fixes #2165 

## Description of Changes

* Return an error when trying to set cpu_template on aarch64 since it is not supported.
* Add to unit tests of parsing PUT machine configuration to make sure the error is returned on aarch64.
* Modify unit tests that test setting machine config making them platform-specific.

Now trying to set the `cpu_template` on aarch64 by running:
```bash 
curl --unix-socket /tmp/firecracker.socket -i  -X PUT "http://localhost/machine-config"  -H "accept: application/json"  -H "Content-Type: application/json"  -d "{ \"vcpu_count\": 1, \"mem_size_mib\": 32, \"ht_enabled\": false, \"cpu_template\": \"T2\" }"
```
will return the following error:
```bash
{"fault_message":"cpu_template is not supported on aarch64"}
```
While running the same request on an x86 machine will work normally.

- [x] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by ahmedaabouzied** [comment]
I see that the `test_snapshot_basic` fails:
```bash

=================================== FAILURES ===================================
  | ____________________________ test_5_full_snapshots _____________________________
  | integration_tests/functional/test_snapshot_basic.py:255: in test_5_full_snapshots
  | test_matrix.run_test(_test_seq_snapshots)
  | framework/matrix.py:150: in run_test
  | self._backtrack(test_fn, [])
  | framework/matrix.py:125: in _backtrack
  | self._backtrack(test_fn, cartesian_product)
  | framework/matrix.py:125: in _backtrack
  | self._backtrack(test_fn, cartesian_product)
  | framework/matrix.py:125: in _backtrack
  | self._backtrack(test_fn, cartesian_product)
  | framework/matrix.py:114: in _backtrack
  | self._run_test_fn(cartesian_product, test_fn)
  | framework/matrix.py:136: in _run_test_fn
  | test_fn(self._context)
  | integration_tests/functional/test_snapshot_basic.py:122: in _test_seq_snapshots
  | check_guest_connections(microvm, path, vm_blob_path, blob_hash)
  | framework/utils_vsock.py:229: in check_guest_connections
  | assert ecode == 0
  | E   AssertionError
  | ------------------------------ Captured log call -------------------------------
  | 23:20:55 snapshot_sequence: INFO Testing SnapshotType.FULL with microvm: "2vcpu_512mb.json", kernel vmlinux-4.14.bin, disk ubuntu-18.04.ext4
  | 23:20:55 retry.api: WARNING [Errno 2] No such file or directory: '/srv/jailer/firecracker/93548a95-3c9b-4309-b6f4-c60ac2289e57/root/run/firecracker.socket', retrying in 0.2 seconds...
  | 23:20:58 retry.api: WARNING , retrying in 0.1 seconds...
  | 23:20:58 retry.api: WARNING , retrying in 0.1 seconds...
  | 23:20:59 snapshot_sequence: INFO Create SnapshotType.FULL #0.
  | 23:21:00 snapshot_sequence: INFO Load snapshot #0, mem /srv/jailer/firecracker/93548a95-3c9b-4309-b6f4-c60ac2289e57/root/snapshot/vm.mem
  | 23:21:00 retry.api: WARNING , retrying in 0.1 seconds...
  | 23:21:08 snapshot_sequence: INFO Create snapshot #1.
  | 23:21:08 snapshot_sequence: INFO Load snapshot #1, mem /srv/jailer/firecracker/c81b2edb-cde5-492b-abea-4604aba73a11/root/snapshot/vm.mem
  | 23:21:08 retry.api: WARNING , retrying in 0.1 seconds...
  | 23:21:25 snapshot_sequence: INFO Create snapshot #2.
  | 23:21:25 snapshot_sequence: INFO Load snapshot #2, mem /srv/jailer/firecracker/933ec3fb-59db-40d5-a026-247b12a3dc50/root/snapshot/vm.mem
  | 23:21:25 retry.api: WARNING [Errno 2] No such file or directory: '/srv/jailer/firecracker/0d970e6e-5371-49de-b611-a9b311245a25/root/run/firecracker.socket', retrying in 0.2 seconds...
  | 23:21:42 snapshot_sequence: INFO Create snapshot #3.
  | 23:21:43 snapshot_sequence: INFO Load snapshot #3, mem /srv/jailer/firecracker/0d970e6e-5371-49de-b611-a9b311245a25/root/snapshot/vm.mem
  | 23:21:43 retry.api: WARNING [Errno 2] No such file or directory: '/srv/jailer/firecracker/4493aaf7-d4e5-41ac-91ec-d3df6588484c/root/run/firecracker.socket', retrying in 0.2 seconds...
  | =========================== short test summary info ============================
FAILED integration_tests/functional/test_snapshot_basic.py::test_5_full_snapshots
```
I'm gonna check it out

File: src/api_server/src/parsed_request.rs [hunk 1]
```diff
@@ -662,23 +662,45 @@ pub(crate) mod tests {
...
+                        \"vcpu_count\": 0, \
+                        \"mem_size_mib\": 0, \
+                        \"ht_enabled\": true \
+                    }",
+                )
+                .unwrap();
+            assert!(connection.try_read().is_ok());
+            let req = connection.pop_parsed_request().unwrap();
+            assert!(ParsedRequest::try_from_request(&req).is_ok());
+        }
```
Comment (serban300) [inline src/api_server/src/parsed_request.rs:703]: This 2 pieces of code are a bit redundant. Can we just build the string differently depending on the architecture ?

Comment (ahmedaabouzied) [reply src/api_server/src/parsed_request.rs]: Yes, that's a valid point

Comment (ahmedaabouzied) [reply src/api_server/src/parsed_request.rs]: Fixed it

**Comment by ahmedaabouzied** [comment]
Hey, @andreeaflorescu, Does running the x86 and aarch64 tests require your approval? Both test suites seem to be stuck on Pending.

File: src/api_server/src/parsed_request.rs (hunk 1 above)
Comment (serban300) [reply src/api_server/src/parsed_request.rs]: Another option would be something like 

```
                [
                    "PUT /machine-config HTTP/1.1\r\n\
                    Content-Type: application/json\r\n",
                    #[cfg(target_arch = "x86_64")]
                    "Content-Length: 58\r\n\r\n{ ",
                    #[cfg(target_arch = "aarch64")]
                    "Content-Length: 80\r\n\r\n{ ",
                    "\"vcpu_count\": 0, \
                    \"mem_size_mib\": 0, \
                    \"ht_enabled\": true, ",
                    #[cfg(target_arch = "x86_64")]
                    "\"cpu_template\": \"C3\" \
                    }",
                ]
                .concat()
                .as_bytes(),
```

Sine the strings are also quite redundant. Not sure which version is more readable though.

**Comment by gc-plp** [comment]
Hi @ahmedaabouzied. 

There was an error on our side that was causing the problem in running the tests. 

It's been fixed and tests should be running now.

Thanks for the PR!

File: src/api_server/src/parsed_request.rs (hunk 1 above)
Comment (ahmedaabouzied) [reply src/api_server/src/parsed_request.rs]: I think that the current implementation is more readable. Having the attributes inside the request payload is a bit confusing, don't you think?

**Review by acatangiu — DISMISSED** [review]

File: src/api_server/src/request/machine_configuration.rs [hunk 2]
```diff
@@ -65,25 +76,65 @@ mod tests {
...
+                mem_size_mib: Some(1024),
+                ht_enabled: Some(true),
+                cpu_template: Some(CpuFeaturesTemplate::T2),
+                track_dirty_pages: true,
+            };
+
+            match vmm_action_from_request(parse_put_machine_config(&Body::new(body)).unwrap()) {
+                VmmAction::SetVmConfiguration(config) => assert_eq!(config, expected_config),
+                _ => panic!("Test failed."),
+            }
```
Comment (serban300) [inline src/api_server/src/request/machine_configuration.rs:102]: This seems identical for x86_64 and arm. Should we put it outside the conditional blocks ?

Comment (ahmedaabouzied) [reply src/api_server/src/request/machine_configuration.rs:102]: Sure .. will do that

**Review by dianpopa — CHANGES_REQUESTED** [review]
Given [this check in](https://github.com/firecracker-microvm/firecracker/pull/2190/files#diff-7b4a60ff5459fcd2c99007305e885d50aeb1212aba22f17559c1f5e5f9d377e1R53) the patch function associated with the machine-configuration, it seems that a patch request will fail all the time for aarch64. We need to solve this too.

**Comment by dianpopa** [comment]
@serban300 @acatangiu take another look, pls!

**Review by acatangiu — APPROVED** [review]

File: tests/integration_tests/functional/test_api.py [hunk 3]
```diff
@@ -125,8 +136,9 @@ def test_api_put_update_pre_boot(test_microvm_with_api):
     mem_size_mib = microvm_config_json['mem_size_mib']
     assert response_json['mem_size_mib'] == mem_size_mib
 
-    cpu_template = str(microvm_config_json['cpu_template'])
-    assert response_json['cpu_template'] == cpu_template
+    if platform.machine() != 'aarch64':
```
Comment (serban300) [inline tests/integration_tests/functional/test_api.py:139]: Nit: I would rather check if `platform.machine() == 'x86_64'` here. Since we only support templates for x86_64.

File: tests/integration_tests/functional/test_api.py [hunk 4]
```diff
@@ -100,16 +100,27 @@ def test_api_put_update_pre_boot(test_microvm_with_api):
...
         'track_dirty_pages': True
     }
-    response = test_microvm.machine_cfg.put(
-        vcpu_count=microvm_config_json['vcpu_count'],
-        ht_enabled=microvm_config_json['ht_enabled'],
-        mem_size_mib=microvm_config_json['mem_size_mib'],
-        cpu_template=microvm_config_json['cpu_template'],
-        track_dirty_pages=microvm_config_json['track_dirty_pages']
-    )
+    if platform.machine() != 'aarch64':
```
Comment (serban300) [inline tests/integration_tests/functional/test_api.py:105]: Nit: I would rather check if `platform.machine() == 'x86_64'` here. Since we only support templates for x86_64

**Comment by dianpopa** [comment]
Addressed latest comments, @serban300 @acatangiu PTAL, thanks!|

**Comment by ahmedaabouzied** [comment]
Are there any comments left for me to address? .. I only get to work on this over the weekend so I'm sorry for these delayed replies.

**Review by serban300 — APPROVED** [review]

**Comment by dianpopa** [comment]
> Are there any comments left for me to address? .. I only get to work on this over the weekend so I'm sorry for these delayed replies. 

Hi @ahmedaabouzied ,

We are just waiting for the second reviewer to get the PR merged. No work needed from your side. Thanks for your involvement!

**Review by acatangiu — APPROVED** [review]
