### PR TITLE
kvm crate: fix arm build

### LINKED ISSUE #949: Fix arm build
Right now the build on arm due to:
- CpuId clone being implemented for all architectures and not only for x86_64
- no kernel_load function on arm64
- no dirty log pages on arm64

### PR DESCRIPTION
**Pull request by andreeaflorescu**
Issue #, if available: Fixes #949 

Description of changes:
Fixed build on arm.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
I would also like to add a build test with cross compilation using `aarch64-unknown-linux-musl` target.
I discovered that there are some other build errors, so we might one to fix those as well and add the test and fixes in a single PR:
```bash
    --> vmm/src/lib.rs:1118:41                                                                                                                                                                                                                                                     
     |                                                                                                                                                                                                                                                                             
1118 |         let entry_addr = kernel_loader::load_kernel(                                                                                                                                                                                                                        
     |                                         ^^^^^^^^^^^ not found in `kernel_loader`  
error[E0599]: no method named `get_dirty_page_count` found for type `&mut Vmm` in the current scope                                                                                                                                                                                
   --> vmm/src/lib.rs:839:49                                                                                                                                                                                                                                                       
    |                                                                                                                                                                                                                                                                              
839 |             METRICS.memory.dirty_pages.add(self.get_dirty_page_count());                                                                                                                                                                                                     
    |                                                 ^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                   
error[E0599]: no method named `configure` found for type `vstate::Vcpu` in the current scope                                                                                                                                                                                       
   --> vmm/src/lib.rs:966:18                                                                                                                                                                                                                                                       
    |                                                                                                                                                                                                                                                                              
966 |             vcpu.configure(&self.vm_config, entry_addr, &self.vm)                                                                                                                                                                                                            
    |                  ^^^^^^^^^                                                                                                                                                                                                                                                   
    |                                                                                                                                                                                                                                                                              
   ::: vmm/src/vstate.rs:190:1                                                                                                                                                                                                                                                     
    |                                                                                                                                                                                                                                                                              
190 | pub struct Vcpu {                                                                                                                                                                                                                                                            
    | --------------- method `configure` not found for this                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                   
error: aborting due to 3 previous errors  
```

**Comment by andreeaflorescu** [comment]
I fixed the other errors as well. Left to do: add integration test with cross compilation using `aarch64-unknown-linux-musl`.

File: vmm/src/lib.rs [hunk 1]
```diff
@@ -1673,10 +1684,10 @@ impl Vmm {
         LOGGER.set_include_origin(api_logger.show_log_origin, api_logger.show_log_origin);
         LOGGER.set_include_level(api_logger.show_level);
 
-        let options = match api_logger.options {
-            Value::Array(options) => options,
-            _ => vec![],
-        };
+        #[cfg(target_arch = "aarch64")]
+        let options: &Vec<Value> = &vec![];
```
Comment (aghecenco) [inline vmm/src/lib.rs]: This will prevent any future log options from being configured on ARM. I think it would be cleaner to remove the `LogDirtyPages` enum variant for `aarch64` and fail at deserialization. Something like:
```diff
iff --git a/logger/src/lib.rs b/logger/src/lib.rs
index b2059b9..fe8ddbe 100644
--- a/logger/src/lib.rs
+++ b/logger/src/lib.rs
@@ -209,6 +209,7 @@ enum Destination {
 #[repr(usize)]
 pub enum LogOption {
     /// Enable KVM dirty page tracking and a metric that counts dirty pages.
+    #[cfg(target_arch = "x86_64")]
     LogDirtyPages = 1,
 }
 ```

File: vmm/src/vmm_config/logger.rs [hunk 2]
```diff
@@ -41,6 +41,7 @@ pub struct LoggerConfig {
     #[serde(default)]
     pub show_log_origin: bool,
     /// Additional logging options.
+    #[cfg(target_arch = "x86_64")]
```
Comment (aghecenco) [inline vmm/src/vmm_config/logger.rs]: I'd rather not remove it completely - who knows what future log options will be needed for ARM?

File: src/main.rs [hunk 3]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 // SPDX-License-Identifier: Apache-2.0
 
+#[cfg(target_arch = "x86_64")]
```
Comment (aghecenco) [inline src/main.rs]: Maybe link to an issue tracking this. We'll need backtrace eventually.

File: .cargo/config [hunk 4]
```diff
@@ -5,4 +5,5 @@ target = "x86_64-unknown-linux-musl"
 # On aarch64 musl depends on some libgcc functions (i.e `__addtf3` and other `*tf3` functions) for logic that uses
 # long double. Such functions are not builtin in the rust compiler, so we need to get them from libgcc.
 # No need for the `crt_static` flag as rustc appends it by default.
-rustflags = [ "-C", "link-arg=-lgcc" ]
+linker = "aarch64-linux-gnu-gcc"
+rustflags = [ "-C", "link-arg=-lgcc" ]
```
Comment (aghecenco) [inline .cargo/config]: nit: add newline

File: tests/integration_tests/build/test_build.py [hunk 5]
```diff
@@ -59,3 +59,16 @@ def test_build_release_with_features(test_session_root_path):
         '--features "{}"'.format('vsock'),
         '--release'
     )
+
+
+def test_arm_build_release(test_session_root_path):
+    """Test if a release-mode build works for supported features."""
```
Comment (aghecenco) [inline tests/integration_tests/build/test_build.py]: nit: the comment does not match the test name, it refers to generic supported features.

File: vmm/src/lib.rs (hunk 1 above)
Comment (andreeaflorescu) [reply vmm/src/lib.rs]: I don't think you can have an empty enum. It will generate an error. But I can try this.

File: src/main.rs (hunk 3 above)
Comment (andreeaflorescu) [reply src/main.rs]: I'll add an issue.

File: vmm/src/lib.rs (hunk 1 above)
Comment (andreeaflorescu) [reply vmm/src/lib.rs]: `LogOption` has its variants as usize. We can't have an empty enum in this case:
```
error[E0084]: unsupported representation for zero-variant enum                                                                                                                                                                                                                     
   --> logger/src/lib.rs:215:1                                                                                                                                                                                                                                                     
    |                                                                                                                                                                                                                                                                              
215 |   #[repr(usize)]                                                                                                                                                                                                                                                             
    |   ^^^^^^^^^^^^^^                                                                                                                                                                                                                                                             
216 | / pub enum LogOption {                                                                                                                                                                                                                                                       
217 | |     /// Enable KVM dirty page tracking and a metric that counts dirty pages.                                                                                                                                                                                               
218 | |     #[cfg(target_arch = "aarch64")]                                                                                                                                                                                                                                        
219 | |     LogDirtyPages = 1,                                                                                                                                                                                                                                                     
220 | | }                                                                                                                                                                                                                                                                          
    | |_- zero-variant enum 
``` 
I say we leave it as is for the moment and in case we want to add different options that are also valid on arm, we can make this change then.

File: src/main.rs (hunk 3 above)
Comment (andreeaflorescu) [reply src/main.rs]: https://github.com/firecracker-microvm/firecracker/issues/955
