### PR TITLE
[v0.22.1] Fix serial memory allocation issue.

### LINKED ISSUE #2177: Firecracker serial console emulation may allocate an unbounded amount of memory
We have identified an issue in the Firecracker serial console emulation of all Firecracker versions up to v0.21.2 and Firecracker v0.22.0
 
### Issue Description
 
The Firecracker implementation of the serial console emulation allows buffering of an unlimited number of bytes when data is written to the Firecracker process standard input at a high rate.
 
### Impact
 
Firecracker customers that forward the standard input of the Firecracker process to untrusted users can become subject to DoS attacks. If memory limits are not imposed on the Firecracker process, this might impair other microVMs on the same host from allocating memory, potentially becoming an availability issue.
 
Serial output generated by the guest can’t trigger the issue.
 
### Affected Systems
 
Firecracker versions v0.22.0 and v0.21.2, while all older releases might be impacted.
 
## Mitigation
 
Impact can be mitigated by applying memory limits to the Firecracker process or by applying a rate limit when writing to the Firecracker process standard input.
 
Customers may apply:
Patched binaries mitigating this issue have been released as Firecracker v0.21.3[1] and Firecracker v0.22.1[2].
If you are using Firecracker versions up to v0.21.2 or Firecracker v0.22.0, we recommend you apply the provided fix.
 
[1] https://github.com/firecracker-microvm/firecracker/releases/tag/v0.21.3
[2] https://github.com/firecracker-microvm/firecracker/releases/tag/v0.22.1

### PR DESCRIPTION
**Pull request by sandreim**
## Reason for This PR

Fixes #2177

## Description of Changes

Provided in commit messages.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

File: src/devices/src/legacy/serial.rs [hunk 1]
```diff
@@ -236,29 +246,112 @@ impl Serial {
...
-            let mut out = [0u8; 32];
-            return input.read(&mut out).and_then(|count| {
-                if count > 0 {
-                    self.raw_input(&out[..count])?;
-                    Ok(count)
-                } else {
-                    Ok(0)
-                }
-            });
+            let mut out = vec![0u8; avail_cap];
```
Comment (georgepisaltu) [inline src/devices/src/legacy/serial.rs:267]: I think this should be a member of the struct as the constant allocation and zeroing of the memory is costly, but this is an optimization which we can implement later and is not related to the security issue.

File: src/devices/src/legacy/serial.rs [hunk 2]
```diff
@@ -286,53 +379,80 @@ impl BusDevice for Serial {
...
-                if count == 0 && unregister_condition {
-                    // Unregister the serial input source.
-                    match ev_mgr.unregister(supported_event.fd()) {
-                        Ok(_) => warn!("Detached the serial input due to peer error/close."),
-                        Err(e) => error!(
-                            "Peer is unreachable. Could not detach the serial input: {:?}",
-                            e
-                        ),
+                // Handle EOF if the event came from the input source.
+                if input_fd == event.fd() && count == 0 {
```
Comment (georgepisaltu) [inline src/devices/src/legacy/serial.rs:415]: Should we handle the case where `input_fd != event.fd()`?

File: tests/integration_tests/functional/test_serial_io.py [hunk 3]
```diff
@@ -68,11 +74,57 @@ def test_serial_console_login(test_microvm_with_ssh):
...
+
+    # Open an fd for firecracker process terminal.
+    tty_path = f"/proc/{microvm.jailer_clone_pid}/fd/0"
+    tty_fd = os.open(tty_path, os.O_RDWR)
+
+    # Check if the total memory size changed.
+    before_size = get_total_mem_size(microvm.jailer_clone_pid)
+    send_bytes(tty_fd, 100000000, timeout=1)
+    after_size = get_total_mem_size(microvm.jailer_clone_pid)
+    assert before_size == after_size, "The memory size of the " \
```
Comment (acatangiu) [inline tests/integration_tests/functional/test_serial_io.py:126]: this is prone to false positives: process used memory can slightly change due to unrelated reasons

we can address this incrementally since worst that can happen are false positives - not blocking this PR because of it

**Review by acatangiu — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]
A few nits, can merge and come back to them later.
