### PR TITLE
Kick vsock during VM resume

### LINKED ISSUE #4736: [Bug] Title
# Describe the bug

Firecracker’s VSock connection reset is not working as expected after resuming from a snapshot. Specifically, the ongoing read syscall in the guest VM does not get interrupted, and the socat instance continues running instead of exiting due to the VSock connection reset.

## To Reproduce

1. Start Firecracker
2. Create a VM with a VSock
3. Start a VSock-over-UDS listener on the host with `socat`
4. In the guest VM, connect to the listener on the host through VSock with `socat`
5. Pause the VM and create a snapshot
6. Stop the listener on the host
7. Resume the VM

The `socat` instance continues running and the ongoing `read` syscall does not get interrupted/the connection reset has no effect. New `read` and `write` syscalls however fail as expected (which can be caused by e.g. pressing <kbd>Enter</kbd> in `socat`), causing an EOF & thus causing `socat` to exit as expected.

For the full reproduction steps, please see [loopholelabs/firecracker-vsock-snapshot-reset-bug-reproducer](https://github.com/loopholelabs/firecracker-vsock-snapshot-reset-bug-reproducer). This includes the helper scripts and assets (kernel, rootfs) to reproduce the bug.

## Expected behaviour

The [Firecracker VSock docs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/snapshotting/snapshot-support.md#vsock-device-limitation) state:

> Firecracker handles sending the `reset` event to the vsock driver, thus the customers are no longer responsible for closing active connections.

From our reading, this should mean that the `socat` instance running inside the guest VM, which has an ongoing `read` syscall, exits due to the VSock connection being reset & the `read` syscall being interrupted.

## Environment

- Firecracker version: [Firecracker v1.7.0](https://github.com/firecracker-microvm/firecracker/releases/tag/v1.7.0)
- Host and guest kernel versions: Host `6.10.4-200.fc40.x86_64`, guest `6.1.89`
- Rootfs used: Buildroot 2024.02.5. See the [loopholelabs/firecracker-vsock-snapshot-reset-bug-reproducer](https://github.com/loopholelabs/firecracker-vsock-snapshot-reset-bug-reproducer) for more details and the specific rootfs being used - this is also reproducible with Ubuntu and Alpine rootfses.
- Architecture: `x86_64`
- Any other relevant software versions: The host is Fedora 40 on a Intel i7-1280P.

## Additional context

How has this bug affected you/what are you trying to achieve: This bug affects the [Drafter Agent System](https://github.com/loopholelabs/drafter/blob/main/cmd/drafter-agent/main.go), which expects Firecracker to kill the active connection before it re-`dial`s the host after a resume. Without the connection being killed by Firecracker, this does not work.

Do you have any idea of what the solution might be: Not a solution, but a workaround we've been trying to use is manually stopping the connection ourselves _before_ snapshotting, but this causes a race condition on resume because the `dial` loop in the guest will sometimes be killed by the Firecracker `reset`ing the (new) connections after a resume. We've also been investigating a kernel return probe `kprobe/virtio_vsock_reset_sock` to try and hold off with re-`dial`ing after a resume until Firecracker has reset the connections if we're closing them ourselves before suspending, but preferably we would simply re-`dial` after Firecracker resets the active connection/interrupts the `read` syscall.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by ShadowCurse**
## Changes
Kick vsock when resuming VM. This ensures that if VM is restored from a snapshot, guest gets a notification to read a queue with `TRANSPORT_RESET_EVENT` inside. This will trigger guest to close all vsock connections. This is expected behavior as vsock devices does not support bringing connections over the snapshot boundary.

## Reason
Fixes #4736

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this
  PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [ ] Commits meet
  [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

File: src/vmm/src/device_manager/mmio.rs [hunk 1]
```diff
@@ -486,6 +486,18 @@ impl MMIODeviceManager {
                         // so for Vsock we don't support connection persistence through snapshot.
                         // Any in-flight packets or events are simply lost.
                         // Vsock is restored 'empty'.
+                        // The only reason we still `kick` it is to make guest process
+                        // `TRANSPORT_RESET_EVENT` event we sent during snapshot creation.
+                        let vsock = virtio
+                            .as_mut_any()
+                            .downcast_mut::<crate::devices::virtio::vsock::Vsock<
+                                crate::devices::virtio::vsock::VsockUnixBackend,
+                            >>()
```
Comment (roypat) [inline src/vmm/src/device_manager/mmio.rs:495]:
```suggestion
                            .downcast_mut::<Vsock<VsockUnixBackend>>()
```

File: tests/integration_tests/functional/test_vsock.py [hunk 2]
```diff
@@ -215,3 +218,93 @@ def test_vsock_transport_reset(
...
+    assert Path(host_socket_path).exists()
+    test_vm.create_jailed_resource(host_socket_path)
+
+    # Create a socat process in the guest which will connect to the host socat
+    guest_socat_commmand = f"tmux new -d 'socat - vsock-connect:2:{ECHO_SERVER_PORT}'"
+    test_vm.ssh.run(guest_socat_commmand)
+
+    # socat should be running in the guest now
+    code, _, _ = test_vm.ssh.run("pidof socat")
+    assert code == 0
```
Comment (roypat) [inline tests/integration_tests/functional/test_vsock.py:267]:
```suggestion
    test_vm.ssh.check_output("pidof socat")
```

File: tests/integration_tests/functional/test_vsock.py [hunk 3]
```diff
@@ -215,3 +218,93 @@ def test_vsock_transport_reset(
...
+    test_vm.start()
+    test_vm.wait_for_up()
+
+    # Generate the random data blob file.
+    blob_path, blob_hash = make_blob(test_fc_session_root_path)
+    vm_blob_path = "/tmp/vsock/test.blob"
+
+    # Set up a tmpfs drive on the guest, so we can copy the blob there.
+    # Guest-initiated connections (echo workers) will use this blob.
+    _copy_vsock_data_to_guest(test_vm.ssh, blob_path, vm_blob_path, bin_vsock_path)
```
Comment (roypat) [inline tests/integration_tests/functional/test_vsock.py:241]: does this test need this?

File: tests/integration_tests/functional/test_vsock.py [hunk 4]
```diff
@@ -215,3 +218,93 @@ def test_vsock_transport_reset(
...
+    # Check that vsock device still works.
+    # Test guest-initiated connections.
+    path = os.path.join(vm2.path, make_host_port_path(VSOCK_UDS_PATH, ECHO_SERVER_PORT))
+    check_guest_connections(vm2, path, vm_blob_path, blob_hash)
+
+    # Test host-initiated connections.
+    path = os.path.join(vm2.jailer.chroot_path(), VSOCK_UDS_PATH)
+    check_host_connections(path, blob_path, blob_hash)
+    metrics = vm2.flush_metrics()
+    validate_fc_metrics(metrics)
```
Comment (roypat) [inline tests/integration_tests/functional/test_vsock.py:310]: this is already covered by a different test

File: tests/integration_tests/functional/test_vsock.py [hunk 5]
```diff
@@ -215,3 +218,93 @@ def test_vsock_transport_reset(
...
+    code, _, _ = test_vm.ssh.run("pidof socat")
+    assert code == 1
+
+    # Kill host socat as it is not useful anymore
+    host_socat.kill()
+    host_socat.communicate()
+
+    # Terminate VM.
+    metrics = test_vm.flush_metrics()
+    validate_fc_metrics(metrics)
```
Comment (roypat) [inline tests/integration_tests/functional/test_vsock.py:283]: This is also covered by a different test

File: src/vmm/src/device_manager/mmio.rs [hunk 6]
```diff
@@ -486,6 +486,18 @@ impl MMIODeviceManager {
                         // so for Vsock we don't support connection persistence through snapshot.
                         // Any in-flight packets or events are simply lost.
                         // Vsock is restored 'empty'.
+                        // The only reason we still `kick` it is to make guest process
```
Comment (pb8o) [inline src/vmm/src/device_manager/mmio.rs:489]: The commit description should be `fix: ` I think.

File: tests/integration_tests/functional/test_vsock.py (hunk 2 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:267]: I wanted to be explicit with `code == 0` or `code == 1`.

File: tests/integration_tests/functional/test_vsock.py (hunk 3 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:241]: I tried to make the test look like a previous one. I don't mind removing it.

File: tests/integration_tests/functional/test_vsock.py (hunk 4 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:310]: Same here

File: tests/integration_tests/functional/test_vsock.py (hunk 5 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:283]: Same here

File: src/vmm/src/device_manager/mmio.rs (hunk 1 above)
Comment (ShadowCurse) [reply src/vmm/src/device_manager/mmio.rs]: fixed

File: tests/integration_tests/functional/test_vsock.py (hunk 3 above)
Comment (roypat) [reply tests/integration_tests/functional/test_vsock.py:241]: I think the existing test is already very bad because it tests 3 different things (connection reset, metrics well-formedness and device works after snapshot), so I'd prefer to not replicate that (and I'd also love for the existing test to be split apart, but that's out of scope here).

Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:241]: I cannot disagree here.

Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py]: removed

File: tests/integration_tests/functional/test_vsock.py (hunk 5 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py:275]: removed

Comment (roypat) [reply tests/integration_tests/functional/test_vsock.py:273]: I can still see it on the github diff :sweat_smile:

File: tests/integration_tests/functional/test_vsock.py (hunk 2 above)
Comment (roypat) [reply tests/integration_tests/functional/test_vsock.py:257]: fair!

File: tests/integration_tests/functional/test_vsock.py (hunk 5 above)
Comment (ShadowCurse) [reply tests/integration_tests/functional/test_vsock.py]: should be gone now

File: src/vmm/src/device_manager/mmio.rs (hunk 6 above)
Comment (ShadowCurse) [reply src/vmm/src/device_manager/mmio.rs:489]: fixed

**Review by roypat — DISMISSED** [review]

File: tests/integration_tests/functional/test_vsock.py (hunk 5 above)
Comment (roypat) [reply tests/integration_tests/functional/test_vsock.py]: yeehaw

File: src/vmm/src/device_manager/mmio.rs (hunk 6 above)
Comment (kalyazin) [reply src/vmm/src/device_manager/mmio.rs:489]: we would need a changelog entry for this, I guess

Comment (ShadowCurse) [reply src/vmm/src/device_manager/mmio.rs:489]: added

File: CHANGELOG.md [hunk 7]
```diff
@@ -18,6 +18,10 @@ and this project adheres to
 
 ### Fixed
 
+- [#4796](https://github.com/firecracker-microvm/firecracker/pull/4796): Fixed
```
[the remark this answers is not in the document]
Comment (ShadowCurse) [reply CHANGELOG.md:21]: added a line there

**Review by kalyazin — DISMISSED** [review]

**Review by roypat — DISMISSED** [review]

**Review by roypat — APPROVED** [review]
