### PR TITLE
aarch64: relax cache topology restrictions

### LINKED ISSUE #2407: Commit 76528ea4 aarch64: setup cache topology regression
# Describe the bug

Commit 76528ea4 aarch64: setup cache topology causes a regression on systems that do not have FDT cache entries.

## To Reproduce

On an aarch64 system with a minimal FDT, run without this commit. 

Then, add the commit. Firecracker will fail with:
`2021-01-08T13:40:26.079775900 [vmnetns:main] Building VMM configured from cmdline json failed: ConfigureSystem(SetupFDT(ReadCacheInfo(InvalidCacheAttr("Line Size", "cannot parse integer from empty string"))))
`

## Expected behaviour

Firecracker should have sufficient defaults to handle this. Also, the code should check for the existence of the required entries in /sysfs and display an error warning instead of the above cryptic message.

## Environment

The FDT is basic, with no cache architecture lines in the FDT. As a result, `/sys/devices/system/cpu/cpu0/cache//index{0..2}` contains only
```
ls /sys/devices/system/cpu/cpu0/cache//index0
level power shared_cpu_list shared_cpu_map type uevent
```

`[ - Firecracker version.]`
Upstream master as of Jan 8. Last commits:
364cf32b (upstream/master, upstream_master) Increase Pytest Coverage
62d7a1b8 Implement Guard Paging Mechanism
bf4796da docs: updating Firecracker maintainers
1026a7c1 CI: modify func for retrieving files

`[ - Host and guest kernel versions.]`
Host: android 4.14
`[ - Rootfs used.]`
N/A
`[ - Architecture.]`
aarch64
`[ - Any other relevant software versions.]`

## Additional context

I have to revert this commit to use firecracker.

`[Author TODO: Do you have any idea of what the solution might be?]`
Check for and supply reasonable defaults for cache params.

## Checks

- [ x] Have you searched the Firecracker Issues database for similar problems?
- [x ] Have you read the existing relevant Firecracker documentation?
- [x ] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by dianpopa**
# Reason for This PR

Fixes #2407 

## Description of Changes

* the commits contain the info needed

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

File: src/arch/src/aarch64/fdt.rs [hunk 1]
```diff
@@ -338,17 +338,27 @@ fn create_cpu_nodes(fdt: &mut Vec<u8>, vcpu_mpidr: &[u64]) -> Result<()> {
...
-                cache.type_.of_cache_sets(),
-                cache.number_of_sets as u32,
-            )?;
+            if cache.size_.is_some() {
+                append_property_u32(
+                    fdt,
+                    cache.type_.of_cache_size(),
+                    cache.size_.unwrap() as u32,
+                )?;
+            }
```
Comment (georgepisaltu) [inline src/arch/src/aarch64/fdt.rs:347]: nit: As this is used multiple times below (and in similar fashion), maybe this can be a function or macro for deduplication and to avoid the use of `unwrap` with an `if let`.

**Review by georgepisaltu — DISMISSED** [review]

**Comment by dianpopa** [comment]
@georgepisaltu addressed your feedback and [pclesr's feedback](https://github.com/firecracker-microvm/firecracker/issues/2407#issuecomment-777470533). PTAL!

File: src/arch/src/aarch64/cache_info.rs [hunk 2]
```diff
@@ -101,9 +118,76 @@ impl CacheType {
...
+        if let Ok(number_of_sets) = self.sysfs_cache(index, "number_of_sets") {
+            self.number_of_sets = Some(number_of_sets.parse::<u16>().map_err(|e| {
+                Error::InvalidCacheAttr("number_of_sets".to_string(), e.to_string())
+            })?);
+        } else {
+            *err_str += if *err_str != "" { ", " } else { "" };
+            *err_str += "number of sets";
+        }
+
+        Ok(())
```
Comment (alindima) [inline src/arch/src/aarch64/cache_info.rs:186]: I find it a little weird to use this `err_str` and return an `Ok` value. Is there a reason we're not using a regular `Error`?

File: src/arch/src/aarch64/cache_info.rs [hunk 3]
```diff
@@ -101,9 +118,76 @@ impl CacheType {
...
+        } else {
+            *err_str += "shared cpu map";
+        }
+
+        if let Ok(coherency_line_size) = self.sysfs_cache(index, "coherency_line_size") {
+            self.line_size = Some(coherency_line_size.parse::<u16>().map_err(|e| {
+                Error::InvalidCacheAttr("coherency_line_size".to_string(), e.to_string())
+            })?);
+        } else {
+            *err_str += if *err_str != "" { ", " } else { "" };
```
Comment (alindima) [inline src/arch/src/aarch64/cache_info.rs:166]: we can simplify this logic by simply adding a comma after each append operation, and pop the last comma right before returning

File: src/arch/src/aarch64/cache_info.rs [hunk 4]
```diff
@@ -318,24 +356,208 @@ mod tests {
...
+        );
+    }
+
+    #[test]
+    fn test_sysfs_read_caches() {
+        let mut l1_caches: Vec<CacheInfo> = Vec::new();
+        let mut non_l1_caches: Vec<CacheInfo> = Vec::new();
+        // We use sysfs for extracting the cache information.
+        assert!(sysfs_read_caches(&mut l1_caches, &mut non_l1_caches).is_ok());
+        assert_eq!(l1_caches.len(), 2);
```
Comment (alindima) [inline src/arch/src/aarch64/cache_info.rs:560]: Are these assumptions we're willing to make? These depend on the cache topology of the host, right?

If somebody is running these unit tests on another machine that does not have these, they will run into errors I'm assuming.

Can we somehow mock the sysfs for this test?

Comment (dianpopa) [reply src/arch/src/aarch64/cache_info.rs]: Indeed, these asserts depend on the host configuration and they might fail when run on other machines. I removed them.
Mocking a sysfs is not quite obvious given that `sysfs_read_caches` (the function that we are testing) constructs the `cache` object inside it and so I do not have access to the `cache_dir` field.

**Review by dianpopa — COMMENTED** [review]
@alindima @georgepisaltu I addressed your latest feedback, please give it another look. Thanks

File: src/arch/src/aarch64/cache_info.rs (hunk 2 above)
Comment (alindima) [reply src/arch/src/aarch64/cache_info.rs:195]: I understand what you're saying. However, I still find it confusing to have an `err_str` with an `Ok()` value.
Can't we distinguish the error types in the caller of this function? We can then match on the returned Error and decide whether it's a soft error (one that does not kill the process) or a hard error.

File: src/arch/src/aarch64/cache_info.rs (hunk 4 above)
Comment (alindima) [reply src/arch/src/aarch64/cache_info.rs]: I see. However, can't we mock the `cache_dir` by implementing the `Default` trait in the test mod with a custom path?

**Review by dianpopa — COMMENTED** [review]
Regarding https://github.com/firecracker-microvm/firecracker/pull/2438#discussion_r587413612, re-implementing `Default` in the tests has a tricky part associated. `TempDir` will [remove the associated path once it goes out of scope](https://github.com/rust-vmm/vmm-sys-util/blob/master/src/unix/tempdir.rs#L26). So, when `sysfs_read_caches` will try to make use of `cache_dir` will crash. Unfortunately, the `vmm-sys-util` implementation of `TempDir` does not have support for making the path persist after drop. 
Now, that I think about the big picture, this function is also called from the fdt code which will also obtain an FDT specific to the machine that our CI is run on (i.e m6g). So, my proposal here is to tackle this separately as part of this [issue](https://github.com/firecracker-microvm/firecracker/issues/2492) since it has a larger scope, WDYT?

File: src/arch/src/aarch64/cache_info.rs (hunk 2 above)
Comment (alindima) [reply src/arch/src/aarch64/cache_info.rs:203]: looks good

**Review by alindima — APPROVED** [review]

**Comment by alindima** [comment]
> Regarding [#2438 (comment)](https://github.com/firecracker-microvm/firecracker/pull/2438#discussion_r587413612), re-implementing `Default` in the tests has a tricky part associated. `TempDir` will [remove the associated path once it goes out of scope](https://github.com/rust-vmm/vmm-sys-util/blob/master/src/unix/tempdir.rs#L26). So, when `sysfs_read_caches` will try to make use of `cache_dir` will crash. Unfortunately, the `vmm-sys-util` implementation of `TempDir` does not have support for making the path persist after drop.
> Now, that I think about the big picture, this function is also called from the fdt code which will also obtain an FDT specific to the machine that our CI is run on (i.e m6g). So, my proposal here is to tackle this separately as part of this [issue](https://github.com/firecracker-microvm/firecracker/issues/2492) since it has a larger scope, WDYT?

I agree

**Review by alindima — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]
