### PR TITLE
Fixed brand string not supporting THz

### LINKED ISSUE #546: Brand string does not support THz unit
As per Intel documentation, https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf, the frequency supports three units: Mhz, Ghz and Thz. However, our brand string implementation when looking for the frequency, does not take into account if the frequency is of `THz` type.

### PR DESCRIPTION
**Pull request by georgepisaltu**
Issue #, if available: fixes #546 

Description of changes: Fixed an issue where the brand string from cpuid did not display the
correct clock frequency of the cpu when it was provided in THz.

Signed-off-by: George Pisaltu <gpl@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: cpuid/src/brand_string.rs [hunk 1]
```diff
@@ -206,50 +206,99 @@ impl BrandString {
...
-                Some((_, &ch)) => {
-                    if ch != b'M' && ch != b'G' {
-                        continue;
+        // The algorithm for matching the regular expression above is based
+        // on a Moore machine, and 'stage' represents the current state of
+        // the machine
+        enum Stages {
+            /// Initial state, looking for a digit.
+            Initial,
+            /// Found integer part of the frequency
```
Comment (acatangiu) [inline cpuid/src/brand_string.rs]: nit: comments should end in fullstop `.` - applicable to all comments added by this commit.

File: cpuid/src/brand_string.rs [hunk 2]
```diff
@@ -206,50 +206,99 @@ impl BrandString {
...
+            /// Found the decimal part
+            FoundFreqDecimalPart,
+            /// Found the unit size
+            FoundFreqUnitSize,
+            /// Found the H in 'Hz'
+            FoundH,
+        };
+
+        let mut freq_start = 0;
+        let mut second_start = 0;
```
Comment (acatangiu) [inline cpuid/src/brand_string.rs]: nit: rename this to `decimal_start` or something more explanatory.

File: cpuid/src/brand_string.rs [hunk 3]
```diff
@@ -395,5 +440,17 @@ mod tests {
...
+        let multiple_points_bstr = BrandString::from_bytes_unchecked(b"50.5.20GHz");
+        assert_eq!(multiple_points_bstr.find_freq().unwrap(), b"5.20GHz");
+
+        let no_decimal_bstr = BrandString::from_bytes_unchecked(b"5GHz");
+        assert!(no_decimal_bstr.find_freq().is_none());
+
+        let interrupted_bstr = BrandString::from_bytes_unchecked(b"500.00M5.20GHz");
+        assert_eq!(interrupted_bstr.find_freq().unwrap(), b"5.20GHz");
+
+        let split_bstr = BrandString::from_bytes_unchecked(b"5.30AMHz");
```
Comment (acatangiu) [inline cpuid/src/brand_string.rs]: Add another string which should be correct, but ridiculous. Something like `1.12bc5.30MaHz2.4.25THz` which should be matched to `4.25Thz`.
