### PR TITLE
devices/net: fix busy spin when no RX buffers are available

### LINKED ISSUE #1049: 100% CPU load when guest's network interface is not up
I have a strange behavior (using v0.15.2):

On the host I create a tap device:
```
ip tuntap add tap0 mode tap
ip link set tap0 up
```

and PUT the info into firecracker
```
curl --unix-socket /run/firecracker/firecracker.socket -i \
    -X PUT 'http://localhost/network-interfaces/eth0' \
    -H 'Accept: application/json'           \
    -H 'Content-Type: application/json'     \
    -d '{
        "iface_id": "eth0",
        "guest_mac": "DE:AD:BE:EF:13:37",
        "host_dev_name": "tap0",
        "allow_mmds_requests": false
    }'
```
Now I'll start the Micro-VM.

Somehow the `firecracker` process keeps running with 100% CPU load, *until* I bring up `eth0` on the guest:
```
# 100% CPU load
ip addr add 172.16.0.2/24 dev eth0
ip link set eth0 up
# CPU idle
ip link set eth0 down
# CPU stays idle
```

From within the VM I see no load:
```
# top
Mem: 10704K used, 104256K free, 80K shrd, 476K buff, 2804K cached
CPU:   0% usr   2% sys   0% nic  96% idle   0% io   0% irq   0% sirq
Load average: 0.00 0.00 0.00 1/38 866
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  866   865 root     R     1524   1%   0   2% top
    8     2 root     IW       0   0%   0   0% [rcu_sched]
  857     1 root     S     4972   4%   0   0% supervise-daemon agetty.ttyS0 --st
    1     0 root     S     2848   2%   0   0% {openrc-init} /sbin/init
  865   859 root     S     1620   1%   0   0% -ash
  859   857 root     S     1516   1%   0   0% /bin/login -- root
   23     2 root     IW       0   0%   0   0% [kworker/0:1]
  251     2 root     SW       0   0%   0   0% [kauditd]
    5     2 root     IW       0   0%   0   0% [kworker/u2:0]
   14     2 root     IW       0   0%   0   0% [kworker/u2:1]
   11     2 root     SW       0   0%   0   0% [cpuhp/0]
   10     2 root     SW       0   0%   0   0% [migration/0]
   13     2 root     IW<      0   0%   0   0% [netns]
   12     2 root     SW       0   0%   0   0% [kdevtmpfs]
    7     2 root     SW       0   0%   0   0% [ksoftirqd/0]
   33     2 root     SW       0   0%   0   0% [oom_reaper]
   34     2 root     IW       0   0%   0   0% [kworker/u2:2]
   70     2 root     IW       0   0%   0   0% [kworker/u2:3]
   96     2 root     IW       0   0%   0   0% [kworker/u2:4]
  136     2 root     IW<      0   0%   0   0% [writeback]
```

Do you have any idea why I have this behavior?
I am using nested virtualization for this. I haven't tested the same on metal yet, but will do.

Best,
Malte

### PR DESCRIPTION
**Pull request by dhrgit**
**Description of changes**:

Fixes #1049 

If the guest virtio-net driver didn't make any RX buffers available, the virtio-net device would busy-spin on tap RX events, unable to consume them, causing host CPU usage to spike needlessly.

This PR changes the virtio-net device behavior to listen to tap RX events, only when there are RX buffers available.

**Note**: this PR is rebased on #1156 , so only the last two commits in here are of interest.

------

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acatangiu** [comment]
Don't we have the same problem with block devices as well?

File: devices/src/virtio/net.rs [hunk 1]
```diff
@@ -154,6 +154,9 @@ pub struct NetEpollHandler {
     acked_features: u64,
     mmds_ns: Option<MmdsNetworkStack>,
     guest_mac: Option<MacAddr>,
+    epoll_fd: RawFd,
+    rx_tap_listening: bool,
+    rx_tap_epoll_token: u64,
```
Comment (acatangiu) [inline devices/src/virtio/net.rs]: We have a horrible design :cry:

File: devices/src/virtio/net.rs [hunk 2]
```diff
@@ -500,6 +503,28 @@ impl NetEpollHandler {
     fn read_tap(&mut self) -> io::Result<usize> {
         self.tap.read(&mut self.rx.frame_buf)
     }
+
+    fn register_tap_rx_listener(&mut self) -> std::result::Result<(), std::io::Error> {
```
Comment (acatangiu) [inline devices/src/virtio/net.rs]: Do we need to use this function to register in `activate()`?

File: devices/src/virtio/net.rs [hunk 3]
```diff
@@ -868,17 +905,6 @@ impl VirtioDevice for Net {
 
             //TODO: barrier needed here maybe?
 
-            epoll::ctl(
-                self.epoll_config.epoll_raw_fd,
-                epoll::ControlOptions::EPOLL_CTL_ADD,
-                tap_raw_fd,
-                epoll::Event::new(epoll::Events::EPOLLIN, self.epoll_config.rx_tap_token),
```
Comment (acatangiu) [inline devices/src/virtio/net.rs]: I see this is no longer registered in `activate()`, but on the `RX_QUEUE` event. Are we sure the driver sends these events on initialization as well? It's my understanding that these events are issued by the driver when it has processed a/some descriptior(s) from the RX queue and there is now room for more.

If we never put anything there, does the spec say that the driver should notify regardless?

Comment (dhrgit) [reply devices/src/virtio/net.rs]: The virt queue buffers are set up after device activation time. Actually, "activation" is a Firecracker-defined term, not mentioned in the virtio spec. We use it to refer to the process we need to go through after device initialization or reset (after the driver sets the DRIVER_OK bit - see section 3.1.1 in the virtio spec, which refers to the device as being "live," after this step).

Populating the virt queues is a subsequent step, performed by the driver, after the device is "live." While I found no "must notify" constraint on the driver in the spec, section 2.6.13 describes the queue hydration procedure, for which the final step is:

> 7. The driver sends an available buffer notification to the device if such notifications are not suppressed.

All in all, IMO we can be as certain as the spec is that, whenever the driver supplies an available buffer (or a batch thereof), we'll get an RX_QUEUE event.

**Comment by dhrgit** [comment]
> Don't we have the same problem with block devices as well?

There's only a single queue for block devices, which is fully driven by the driver. So there's no external events (host-generated) that we could end up spinning on. This is, however, the case for the upcoming vsock.
