### PR TITLE
Exclude msr-tools package on Arm

### LINKED ISSUE #3268: [Bug] Title
# Describe the bug

While testing an ARM instance against Firecracker-go-sdk, the **msr-tools** package failed to be loaded. This package is blocking the creation of a rootfs for an ARM instance.

## To Reproduce

msr-tools is present in `setup_rootfs.sh` from firecracker repository. This script is run during the setup of test tools via firecracker.

## Expected behaviour

Calling out msr-tools package for not supporting ARM, which skips tests for Snapshots that need rootfs with an SSH key.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks

- [ ] Have you searched the Firecracker Issues database for similar problems?
- [ ] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by JonathanWoollett-Light**
Signed-off-by: Jonathan Woollett-Light <jcawl@amazon.co.uk>

## Changes

Excludes `msr-tools` from packages used in `firecracker/resources/tests/setup_rootfs.sh` when not on x86-64.

## Reason

Closes #3268

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [x] New `unsafe` code is documented.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

### CODE REVIEW

File: resources/tests/setup_rootfs.sh [hunk 1]
```diff
@@ -11,7 +11,14 @@ prepare_fc_rootfs() {
     SSH_DIR="$BUILD_DIR/ssh"
     RESOURCE_DIR="$2"
 
-    packages="udev systemd-sysv openssh-server iproute2 msr-tools"
+    packages="udev systemd-sysv openssh-server iproute2"
+
+    # msr-tools is only supported on x86-64.
+    arhc=`uname -m`
```
Comment (dianpopa) [inline resources/tests/setup_rootfs.sh:17]: typo in var name

**Comment by vvejell1** [comment]
LGTM

File: resources/tests/setup_rootfs.sh [hunk 2]
```diff
@@ -11,7 +11,14 @@ prepare_fc_rootfs() {
     SSH_DIR="$BUILD_DIR/ssh"
     RESOURCE_DIR="$2"
 
-    packages="udev systemd-sysv openssh-server iproute2 msr-tools"
+    packages="udev systemd-sysv openssh-server iproute2"
+
+    # msr-tools is only supported on x86-64.
+    arch=`uname -m`
```
Comment (pb8o) [inline resources/tests/setup_rootfs.sh:17]: nit: I think `shellcheck` prefers `$()` (it's a bit more readable to me).

```sh
arch=$(uname -m) 
```

File: resources/tests/setup_rootfs.sh [hunk 3]
```diff
@@ -11,7 +11,14 @@ prepare_fc_rootfs() {
...
+    if [ ${arch} == "x86_64" ]; then
```
Comment (pb8o) [inline resources/tests/setup_rootfs.sh:18]: nit: `"${arch}"`, also from `shellcheck`

**Review by pb8o — APPROVED** [review]

File: resources/tests/setup_rootfs.sh (hunk 2 above)
Comment (vvejell1) [reply resources/tests/setup_rootfs.sh:17]: Yes, you are correct. `arch=$(uname -m)`  will be preferable.

File: resources/tests/setup_rootfs.sh (hunk 3 above)
Comment (vvejell1) [reply resources/tests/setup_rootfs.sh:18]: same with ` "${arch}" ` will be fine

**Review by pb8o — APPROVED** [review]

**Review by zulinx86 — APPROVED** [review]
