### PR TITLE
logger/src, vmm: Fixed typo and added `filter_cpuid` metric

### LINKED ISSUE #1121: filter_cpuid metric isn't incremented anywhere anymore
https://github.com/firecracker-microvm/firecracker/commit/8e2640aa removed the `filter_cpuid` (actually called `fitler_cpuid`, a typo that also needs fixing) from being incremented. It's currently unused. It should be added back in the `Vcpu::configure` call (and renamed).

### PR DESCRIPTION
**Pull request by tamionv**
Issue #, if available: fixes #1121
Description of changes: Fixes a typo where filter_cpuid was called fitler_cpuid. Also fixed an issue where the filter_cpuid metric wasn't incremented anywhere; also, adds an error log in this case.

Signed-off-by: Tamio-Vesa Nakajima tnk@amazon.com

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: vmm/src/vstate.rs [hunk 1]
```diff
@@ -262,7 +262,14 @@ impl Vcpu {
         )
         .map_err(Error::CpuId)?;
 
-        filter_cpuid(&mut self.cpuid, &cpuid_vm_spec).map_err(Error::CpuId)?;
+        filter_cpuid(&mut self.cpuid, &cpuid_vm_spec).map_err(|e| {
+            METRICS.vcpu.filter_cpuid.inc();
+            error!(
+                "Failure in configuring CPUID for vcpu {:?}: {:?}",
```
Comment (aghecenco) [inline vmm/src/vstate.rs]: `self.id` is an `u8` and can be formatted with the `{}` operator:
```suggestion
                "Failure in configuring CPUID for vcpu {}: {:?}",
```

Comment (tamionv) [reply vmm/src/vstate.rs]: Ok, I will fix this
