### PR TITLE
logger: increase metrics count if lock poisoned.

### LINKED ISSUE #1566: logger: inconsistency in metrics count.
Logs and metrics failed count not incremented if the destination (log and metrics) FIFO fd's row lock got poisoned (firecracker just panicked).

### PR DESCRIPTION
**Pull request by KarthikNedunchezhiyan**
Signed-off-by: karthik nedunchezhiyan <karthik.n@zohocorp.com>

## Reason for This PR

- Fixes #1566 
- `log_metrics` returned result of false even successfully written the metrics to a destination.

## Description of Changes

This PR includes

- `missed_log_count` incremented if the FIFO fd's destination lock got poisoned.
- returned result of true if `log_metrics` successfully written the metrics to a destination.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [ ] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [ ] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

File: src/logger/src/lib.rs [hunk 1]
```diff
@@ -547,6 +547,7 @@ impl Logger {
                     METRICS.logger.missed_log_count.inc();
                 }
             } else {
+                METRICS.logger.missed_log_count.inc();
                 panic!("Failed to write to the provided metrics destination due to poisoned lock");
```
Comment (dianpopa) [inline src/logger/src/lib.rs]: I think here should be `Failed to write to the provided log destination due to...`, it is a miss of some previous commit.

**Comment by dianpopa** [comment]
`gitlint` complains about punctuation in title of the commit

File: src/logger/src/lib.rs [hunk 2]
```diff
@@ -566,13 +567,14 @@ impl Logger {
...
-                        write_to_destination(msg, guard)
+                        return write_to_destination(msg, guard)
                             .map_err(|e| {
                                 METRICS.logger.missed_metrics_count.inc();
                                 e
                             })
-                            .map(|()| true)?;
+                            .map(|_| true);
                     } else {
+                        METRICS.logger.missed_metrics_count.inc();
```
Comment (raduiliescu) [inline src/logger/src/lib.rs]: I don't get the purpose of increasing a metric when the program will panic. How does this help?

Comment (acatangiu) [reply src/logger/src/lib.rs]: Generally it does make sense, because our panic handler flushes metrics before ending the process and particular metrics are relevant in crashes.

However, in this particular case, the `panic!` occurs on a poisoned lock wrapping the metrics buf itself, so it is obvious that in such a case, no further metrics can be reported anyway, it would simply `panic` again this time skipping our panic handler (to avoid infinite recursion).

So, yes, this line doesn't have any use.

Comment (KarthikNedunchezhiyan) [reply src/logger/src/lib.rs]: @acatangiu nice catch, Now i started to think if fifo got poisoned then firecracker will stuck in loop?

Comment (acatangiu) [reply src/logger/src/lib.rs]: It really shouldn't but I encourage you to test it.
It should be fairly simple, just make one of the vcpu threads panic while holding that lock. The vmm thread will go through this exact code and test your theory.

File: src/logger/src/lib.rs (hunk 1 above)
Comment (KarthikNedunchezhiyan) [reply src/logger/src/lib.rs]: yes @dianpopa

File: src/logger/src/lib.rs (hunk 2 above)
Comment (KarthikNedunchezhiyan) [reply src/logger/src/lib.rs]: @acatangiu , I tried a code that will cause an infinite panic loop. rust prevented us from looping 😃 .

**Comment by KarthikNedunchezhiyan** [comment]
as like @acatangiu said adding this PR has no use as there is no way to write metrics if lock got poisoned. so, closing this PR 👍

**Comment by dianpopa** [comment]
Hm I do see a use to this PR...the first line of code change counted the fact the the **log** lock got poisoned and we also identified a little bug in the logger code, right? @acatangiu and @raduiliescu ?
@raduiliescu a use case for increasing a metric before crashing is to let users configure alarms on metrics (on logs you cannot do that).

**Comment by acatangiu** [comment]
Yes, the changes to `fn log_helper()` are useful, the changes to `fn log_metrics()` were the ones that were not helping.

File: src/logger/src/lib.rs (hunk 1 above)
Comment (KarthikNedunchezhiyan) [reply src/logger/src/lib.rs]: done 👍

**Comment by KarthikNedunchezhiyan** [comment]
@dianpopa @acatangiu @raduiliescu I have made changes to code as like we discussed above. kindly take another look 🙂
