### PR TITLE
Change vCPU threads exit behavior in order to avoid sigprocmask

### LINKED ISSUE #1456: Occasional KVM_EXIT_SHUTDOWN and bad syscall (14) during VM shutdown
Firecracker-containerd recently updated a test case that previously ran 5 VMs to now run 100 and started seeing the following errors occur in ~0-3 VMs per test case ([issue](https://github.com/firecracker-microvm/firecracker-containerd/issues/358)).

As part of terminating VMs, we tell systemd in the guest to reboot the system. Most of the time this works fine, we see `reboot: machine restart` in the systemd logs and the VMM exits with 0 as expected right after.

Occasionally though, the guest reaches that `reboot: machine restart` line and then we see a few logs lines from Firecracker like:
```
2019-12-06T20:29:30.007995741 [anonymous-instance:INFO] Received KVM_EXIT_SHUTDOWN signal
2019-12-06T20:29:30.008087608 [anonymous-instance:ERROR] Shutting down VM after intercepting a bad syscall (14).
```
Followed by the VMM exiting with code 148. The [KVM_EXIT_SHUTDOWN case](https://github.com/firecracker-microvm/firecracker/blob/b359722c23ec69a27b74fbfe2de434a7caa1a4b5/src/vmm/src/vstate.rs#L586) and bad syscall (which appears to be rt_sigprocmask) ~seem to only ever occur together (never just one or the other)~ and only right after the reboot call should be occurring. 
  * EDIT: I've now very rarely seen `KVM_EXIT_SHUTDOWN` occur without an accompanying `rt_sigprocmask` call that results in the seccomp violation. When `KVM_EXIT_SHUTDOWN` occurs by itself, the VMM exits with 0 with no apparent issues.

Additionally, I don't see this for every VM that exits like that, but am occasionally getting a line like this in dmesg after a run of the test case where failures occur:
```
[10548769.845897] traps: fc_vcpu0[52462] trap invalid opcode ip:527d36 sp:7f7ee67f0590 error:0 in firecracker[400000+1ab000]
```
No idea if it's related or, if it is, why it wouldn't be written every time a VM exits with KVM_EXIT_SHUTDOWN+the bad syscall, but figured it was worth mentioning.

This same behavior occurs in both 0.19 (w/ rust1.35+musl) and a 0.20 binary I built from [here](https://github.com/serban300/firecracker/tree/release) (w/ rust1.38+musl).

Let us know what, if anything, would be helpful for further reproducing or debugging as it seems to be a pretty rare issue. We can run our 100 VM test case with debugging binaries and/or see if it's possible to make docker container reproducer for you to use or something like that.

### PR DESCRIPTION
**Pull request by serban300**
## Reason for This PR

fixes #1456 

## Description of Changes

Don't allow vCPU threads to exit. If they finished execution, they will signal the VMM to exit and then wait forever.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided.
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

File: src/vmm/src/lib.rs [hunk 1]
```diff
@@ -1270,7 +1270,26 @@ impl Vmm {
...
+                    // If the exit_code can't be found on any vcpu, it means that the exit signal
+                    // has been issued by the i8042 controller in which case we exit with
+                    // FC_EXIT_CODE_OK.
+                    let exit_code = self
+                        .vcpus_handles
+                        .iter()
+                        .find_map(|handle| {
+                            match handle
+                                .response_receiver()
+                                .recv_timeout(Duration::from_millis(1))
```
Comment (acatangiu) [inline src/vmm/src/lib.rs]: I think we could spare a few more milliseconds here :smile:

File: src/vmm/src/vstate.rs [hunk 2]
```diff
@@ -774,18 +775,33 @@ impl Vcpu {
...
-                StateMachine::next(Self::exited)
+                self.exit(FC_EXIT_CODE_GENERIC_ERROR)
             }
         }
     }
 
-    // This is the main loop of the `Exited` state.
-    fn exited(&mut self) -> StateMachine<Self> {
+    // Transition to the exited state
+    fn exit(&mut self, exit_code: u8) -> StateMachine<Self> {
```
Comment (acatangiu) [inline src/vmm/src/vstate.rs]: nit: why is this a separate function and not just the `exited` state?

File: src/vmm/src/vstate.rs [hunk 3]
```diff
@@ -718,7 +719,7 @@ impl Vcpu {
                 // Emulation was interrupted, check external events.
                 Ok(VcpuEmulation::Interrupted) => break,
                 // Emulation errors lead to vCPU exit.
-                Err(_) => return StateMachine::next(Self::exited),
+                Err(_) => return self.exit(FC_EXIT_CODE_GENERIC_ERROR),
```
Comment (acatangiu) [inline src/vmm/src/vstate.rs]: In this case, you should change `run_emulation()` to not mark `KVM_EXIT_SHUTDOWN` as an error.
In case of `KVM_EXIT_SHUTDOWN`, we want `FC_EXIT_CODE_OK`.

File: src/vmm/src/lib.rs (hunk 1 above)
Comment (kzys) [reply src/vmm/src/lib.rs]: +1 We actually hit this issue under heavy load due to testing (launching multiple VMs). 10d1f4aa59da50f8d39db9692844740dbacde5e6

Comment (acatangiu) [reply src/vmm/src/lib.rs]: This is an error case and only impacts the return code. We can't be extra generous either and optimize for the error case because then we'd be hurting the common good case by delaying the actual process end by `num_vcpus * timeout`.

Comment (serban300) [reply src/vmm/src/lib.rs]: We shouldn't need more than 1 since the vCPU first writes the response and then it writes to `exit_evt`. But I can increase this number. How many would you suggest ?

File: src/vmm/src/vstate.rs (hunk 3 above)
Comment (serban300) [reply src/vmm/src/vstate.rs]: Yes. I did this in the last commit.

File: src/vmm/src/vstate.rs (hunk 2 above)
Comment (serban300) [reply src/vmm/src/vstate.rs]: Because it needs to receive the `exit_code` as a parameter. From what I understand a `StateFn` can't receive parameters.

File: src/vmm/src/lib.rs (hunk 1 above)
Comment (acatangiu) [reply src/vmm/src/lib.rs]: If `KVM_EXIT_SHUTDOWN` is not returned (as we've seen on certain cpu/kernel-version combinations) we're only relying on the `i8042` exit event which triggers the `Vmm` exit code without having any `Vcpu` write any exit reason. It's a valid case explained by your comment.

Comment (acatangiu) [reply src/vmm/src/lib.rs]: @serban300 is right, no need for bigger timeout.

1. in case of vcpu exit/error: `Vcpu` populates the channel **then** hits the event-fd, so by the time vmm picks up the event the channel data is guaranteed to be there.
2. in case of `i8042`: `Vcpu` doesn't provide data on the channel and Vmm will simply find it empty.

In all cases we don't need to wait.

nit: replace `.recv_timeout()` with `.try_wait()`.

Comment (serban300) [reply src/vmm/src/lib.rs]: Fixed.

**Comment by kzys** [comment]
firecracker-containerd's integration tests are passing with this change!

https://github.com/firecracker-microvm/firecracker-containerd/pull/383

**Comment by acatangiu** [comment]
Actually a `CHANGELOG::#Fixed` entry would also be in order.

**Comment by serban300** [comment]
> Actually a `CHANGELOG::#Fixed` entry would also be in order.

Makes sense. Done.

File: src/vmm/src/vstate.rs (hunk 2 above)
Comment (serban300) [reply src/vmm/src/vstate.rs]: Personally I don't like it too much because exit_code is not generic state for the vCPU. It's just a code that has to be use once, right before exit. It would be really nice if we could send parameters to the state functions. Since it's not possible for the moment, I personally prefer to have the intermediate function `exit()` that receives the exit_code parameter.
