### PR TITLE
Specify network interfaces that accept MMDS requests through `/mmds/config` API

### LINKED ISSUE #2174: Align MMDS configuration and MMDS operation device requirements
## Describe the bug

Per RFC issue #1866 / PR #1883: 

> ... the APIs for MMDS data store creation or MMDS configuration do not output any error if there is no network device configured. However, in terms of its operation, MMDS is not reachable if there is no network device which allows MMDS requests

and 

> The misalignment which might cause customer confusion comes from the fact that the MMDS configuration requirements does not correspond with MMDS operation requirements. I can not say this is a required design choice or simply an arbitrary happening due to unclear requirements. My understanding is that it is not a blocker of any sort for Firecracker usage and configuration since we haven't had any issues with it so far. I also believe that with the advent of the Device-API matrix it will be easier to think for the future in terms of API refinement in this area. Feel free to open any issue on this topic.

## To Reproduce

Issue is identified per @iulianbarbu comments in PR #1883

## Expected behaviour

Configuring MMDS for a uVM without a network device should return an error to the effect that MMDS **operation** requires a network device.

## Environment

- Firecracker version.

```bash
$ firecracker --version
Firecracker v0.21.1
```
- Host and kernel version.
```bash
$ uname -a
Linux desktop.local.lan 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Rootfs used: Not relevant
- Architecture: ` x86_64`

## Additional context

**How has this bug affected you?** Consuming Firecracker errors requires different logic depending on the API-device pair. 

**What are you trying to achieve?** Robust error handling.

**Do you have any idea of what the solution might be?** Single code path for Firecracker API-device pair error handling?

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by luminitavoicu**
# Reason for This PR

Provide a cleaner API for allowing MMDS requests on network interfaces. 
Also fixes #2174

## Description of Changes

- Add a `network_interfaces` field that takes a list of the network interface IDs capable of forwarding packets to the MMDS. Network interface IDs mentioned must be valid at the time of this request. The net device model will reply to HTTP GET requests sent to the MMDS address via the interfaces mentioned. In this case, both ARP requests and TCP segments heading to `ipv4_address` are intercepted by the device model, and do not reach the associated TAP device.
- Remove `allow_mmds_requests` from the body of the request that creates network interfaces.

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [X] All commits in this PR are signed (`git commit -s`).
- [X] The issue which led to this PR has a clear conclusion.
- [X] This PR follows the solution outlined in the related issue.
- [X] The description of changes is clear and encompassing.
- [X] Any required documentation changes (code and docs) are included in this PR.
- [X] Any newly added `unsafe` code is properly documented.
- [X] Any API changes follow the [Runbook for Firecracker API changes][2].
- [X] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [X] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

### CODE REVIEW

File: src/vmm/src/resources.rs [hunk 1]
```diff
@@ -301,18 +301,8 @@ impl VmResources {
...
-                    net_device
-                        .lock()
-                        .expect("Poisoned lock")
-                        .set_mmds_ipv4_addr(ipv4_addr);
-                }),
-                None => (),
-            };
-        })
+        let _ = self.net_builder.build(body)?;
+        Ok(())
```
Comment (dianpopa) [inline src/vmm/src/resources.rs:305]: nit:
```suggestion
        let _ = self.net_builder.build(body)
```

**Review by dianpopa — COMMENTED** [review]
There are some passages from the [mmds doc](../../tree/main/docs/mmds) that need updating, for example this one: https://github.com/firecracker-microvm/firecracker/blob/main/docs/mmds/mmds-user-guide.md#example.

**Comment by luminitavoicu** [comment]
> There are some passages from the [mmds doc](../../tree/main/docs/mmds) that need updating, for example this one: https://github.com/firecracker-microvm/firecracker/blob/main/docs/mmds/mmds-user-guide.md#example.

Indeed, there are many updates needed to the docs. I would prefer to include them in the PR that updates MMDS's behavior, since these changes are tightly coupled with MMDS. WDYT?

**Review by dianpopa — APPROVED** [review]

File: tests/integration_tests/functional/test_api.py [hunk 2]
```diff
@@ -319,6 +298,101 @@ def test_net_api_put_update_pre_boot(test_microvm_with_api):
     assert test_microvm.api_session.is_status_no_content(response.status_code)
 
 
+def test_api_mmds_config(test_microvm_with_api):
```
Comment (raduiliescu) [inline tests/integration_tests/functional/test_api.py:301]: What happens when an interface is configured via /network-interfaces, mmds is enabled on it, and then the interface deleted from /network-interfaces?

Comment (luminitavoicu) [reply tests/integration_tests/functional/test_api.py:301]:
```rust
        // Create `MmdsNetworkStack` and configure the IPv4 address for
        // existing built network devices whose names are defined in the
        // network interface ID list.
        for net_device in self.net_builder.iter_mut() {
            let mut net_device_lock = net_device.lock().expect("Poisoned lock");
            if network_interfaces.contains(net_device_lock.id()) {
                net_device_lock.configure_mmds_network_stack(ipv4_addr);
            } else {
                net_device_lock.disable_mmds_network_stack();
            }
        }
```

This piece of code from `set_mmds_config()` handles this case. We iterate through all network devices attached and if the ID of the net iface is present in the `network_interfaces` list provided through `MmdsConfig`, then we configure it to allow MMDS requests. Otherwise, we disable the MMDS Network Stack from that interface. This ensures that only the interfaces specified in the list accept forwarding requests to MMDS.

Comment (dianpopa) [reply tests/integration_tests/functional/test_api.py:301]: I think Radu was referring to the case where an user appends an interface and then deletes it. We do not offer a delete api endpoint in Firecracker. Also, the patch request on network interface allows updating of the rate limiters only.

**Review by AlexandruCihodaru — APPROVED** [review]
