### PR TITLE
API: log failed api requests

### LINKED ISSUE #1383: Failing API requests do not log the failing reason
When sending invalid/incorrect API requests, their failure message is provided in the HTTP response but not logged.

Add logging for failures.

### PR DESCRIPTION
**Pull request by acatangiu**
## Reason for This PR

Fixes #1383 

## Description of Changes

Failing API requests would report their error message in the HTTP response, but not also log it.
Add the mechanism to also log the detailed error.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`  
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided. 
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [x] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [x] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.
- [x] Either no new `unsafe` code has been added, or, the newly added `unsafe`
      code is unavoidable and properly documented.

### CODE REVIEW

File: api_server/src/parsed_request.rs [hunk 1]
```diff
@@ -160,35 +160,40 @@ pub enum Error {
     SerdeJson(serde_json::Error),
 }
 
+impl std::fmt::Display for Error {
+    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
+        match *self {
+            Error::Generic(_, ref desc) => write!(f, "Error: {}", desc),
```
Comment (iulianbarbu) [inline api_server/src/parsed_request.rs]: Looking on how we will respond for parse request errors to clients, we use a status and a message to describe what happened. I feel that `Error:` prefix it is redundant, in the idea that there is already a response status to describe what happened.

While being redundant in a self describing response, it is useful when searching for errors in logs.

File: api_server/src/lib.rs [hunk 2]
```diff
@@ -225,7 +225,10 @@ impl ApiServer {
             Ok(ParsedRequest::GetMMDS) => self.get_mmds(),
             Ok(ParsedRequest::PatchMMDS(value)) => self.patch_mmds(value),
             Ok(ParsedRequest::PutMMDS(value)) => self.put_mmds(value),
-            Err(e) => e.into(),
+            Err(e) => {
+                info!("{}", e);
```
Comment (iulianbarbu) [inline api_server/src/lib.rs]: Would it be better if we log the errors with `error!`? I think it will make easier to identify logs which corresponds to errors, which will make also easier to describe errors, without any prefix that put a tag on the error message.

Comment (acatangiu) [reply api_server/src/lib.rs]: done

File: api_server/src/parsed_request.rs (hunk 1 above)
Comment (acatangiu) [reply api_server/src/parsed_request.rs]: done
