### PR TITLE
micro_http: fix crash when calling 'GET none ...'

### LINKED ISSUE #2123: [Bug] Firecracker crashes when a malformed GET request is sent to the API server
This issue was reported by Davide Berardi. Thank you for bringing this to our attention! 

## Describe the bug

Firecracker crashes when a malformed GET request is sent to the API server.

## To Reproduce
1. Build the latest Firecracker binary and run `./firecracker --api-sock test.sock`
2. Run `perl -e 'print "GET none HTTP/1.1\r\n\r\n"' | nc -U test.sock`
3. Firecracker will crash:
```
2020-09-06T13:49:51.611205354 [anonymous-instance:ERROR:src/firecracker/src/main.rs:52] Firecracker panicked at 'byte index 1 is out of bounds of ``', src/libcore/str/mod.rs:2196:9
2020-09-06T13:49:51.611276388 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:68] Shutting down VM after intercepting a bad syscall (14).
2020-09-06T13:49:51.611302240 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:116] Shutting down VM after intercepting signal 31, code 1.
```
## Expected behaviour

The API server should reply that the request is invalid.

## Additional context

Issue is caused by the [following line](https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/src/parsed_request.rs#L44) in the request handler execution path.

When `request_uri` is the empty string `""`, the parser will try to access index `[1..]`.

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

### PR DESCRIPTION
**Pull request by gc-plp**
When an HTTP request path does not contain a leading '/' character, the
API server will crash, also killing the Firecracker process.

Reported-by: Davide Berardi <berardi.dav@gmail.com>
Signed-off-by: Gabriel Ionescu <gbi@amazon.com>

## Reason for This PR

Fixes #2123 

## Description of Changes

Avoid indexing starting from `[1..]` when the string is empty.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Review by iulianbarbu — COMMENTED** [review]
Please rephrase the commit description to refer to the leading '/' of a HTTP request _path_.

**Review by georgepisaltu — APPROVED** [review]

File: src/api_server/src/parsed_request.rs [hunk 1]
```diff
@@ -270,6 +277,30 @@ pub(crate) mod tests {
...
+        assert!(connection.try_read().is_ok());
+
+        let req = connection.pop_parsed_request().unwrap();
+        match ParsedRequest::try_from_request(&req) {
+            Err(Error::Generic(StatusCode::BadRequest, err_msg)) => {
+                if err_msg != "GET request cannot have a body." {
+                    panic!("GET request with body.");
+                }
+            }
+            _ => panic!("GET request with body."),
```
Comment (iulianbarbu) [inline src/api_server/src/parsed_request.rs:300]: nit: Is it necessary to check against GET with body as well?

**Review by iulianbarbu — APPROVED** [review]

**Review by georgepisaltu — APPROVED** [review]

File: src/api_server/src/parsed_request.rs (hunk 1 above)
Comment (gc-plp) [reply src/api_server/src/parsed_request.rs]: @iulianbarbu see update, please

**Review by iulianbarbu — APPROVED** [review]
