### PR TITLE
fix `IovDeque` for non 4K pages

### LINKED ISSUE #5217: [Bug] Regression v1.10.0 tap device unreliable and unresponsive
# Describe the bug

A recent Firecracker version seems to have introduced a regression.

The connection via tap device becomes quickly unreliable and unresponsive after boot (however, it works fine for a short time). I am just following the getting started guide, nothing fancy. I am on ARM64.

## To Reproduce

`[Author TODO: Steps to reproduce the behaviour:]`

1. Start Firecracker via `sudo ./firecracker-v1.11.0-aarch64 --config-file firecracker.conf --api-sock ./firecracker.socket`
1. Configure Firecracker via

```
{
  "boot-source": {
    "kernel_image_path": "vmlinux-6.1.128",
    "boot_args": "keep_bootcon console=ttyS0 reboot=k panic=1 pci=off"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "is_root_device": true,
      "is_read_only": false,
      "path_on_host": "ubuntu-24.04.ext4"
    }
  ],
  "machine-config": null,
  "cpu-config": null,
  "balloon": null,
  "network-interfaces": [
    {
      "iface_id": "net1",
      "guest_mac": "06:00:AC:10:00:02",
      "host_dev_name": "tap0"
    }
  ],
  "vsock": null,
  "logger": {
    "log_path": "./firecracker.log",
    "level": "Debug",
    "show_level": true,
    "show_log_origin": true
  },
  "metrics": null,
  "mmds-config": null,
  "entropy": null
}
```
3. Connect via SSH, it will fail after a few attempts

For some reason this config does not parse with v1.10.0. However I am pretty sure this version introduced the bug since it mentions changes with virtio-net.

The bug is not reproducible with v1.9.1

```
sudo ./firecracker-v1.9.1-aarch64 --config-file firecracker.conf --api-sock ./firecracker.socket
```

## Expected behaviour

It remains possible to ssh into the device.

```
ping 172.16.0.2
```

should keep pinging, instead packets get delayed, dropped, etc.

## Environment

`[Author TODO: Please supply the following information):]`

- Firecracker version: v1.10.0
- Host and guest kernel versions: host: 6.14.6-400.asahi.fc41.aarch64+16k, guest: 6.1.128
- Rootfs used: the one from the getting started guide
- Architecture: arm64
- Any other relevant software versions: N/A

## Additional context

`[Author TODO: How has this bug affected you?]`
Not much just trying out Firecracker

`[Author TODO: What are you trying to achieve?]`
Just run the thing

`[Author TODO: Do you have any idea of what the solution might be?]` 
Probably the virtio changes are related

Note that Ashai Linux uses 16K pages, which may have something to do with it

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

According to @Manciukic this has not been reported yet.

### PR DESCRIPTION
**Pull request by ShadowCurse**
## Changes
The `L` const generic was determining the maximum number of `iov`
elements in the `IovDeque`. This cases the issue when the host kernel
uses pages which can contain more entries than `L`. For example usual
4K pages can contain 256 `iov`s while 16K pages can contain 1024 `iov`s.
Current implementation on 16K (and any other bigger than 4K page size)
will continue wrap `IovDeque` when it reaches 256'th element. This
breaks the implementation since elements written past 256'th index will
not be 'duplicated' at the beginning of the queue.

Curren implementation expects this behavior:
```
 page 1 page 2
|ABCD|#|ABCD|
      ^ will wrap here
```

With big page sizes current impl will:
```
 page 1              page2
|ABCD|EFGD________|#|ABCDEFGD________|
     ^ sill wrap here
                   ^ but should wrap here
```

The solution is to calculate the maximum capacity the `IovDeque` can
hold, and use it for wrapping purposes. This capacity is allowed to be
bigger than `L`. The actual used number of entries in the queue will
still be guarded by the `L` parameter used in the `is_full` method.

## Reason
Fixes #5217

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] I have read and understand [CONTRIBUTING.md][3].
- [ ] I have run `tools/devtool checkstyle` to verify that the PR passes the
  automated style checks.
- [ ] I have described what is done in these changes, why they are needed, and
  how they are solving the problem in a clear and encompassing way.
- [ ] I have updated any relevant documentation (both in code and in the docs)
  in the PR.
- [ ] I have mentioned all user-facing changes in `CHANGELOG.md`.
- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] When making API changes, I have followed the
  [Runbook for Firecracker API changes][2].
- [ ] I have tested all new and changed functionalities in unit tests and/or
  integration tests.
- [ ] I have linked an issue to every new `TODO`.

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

### CODE REVIEW

File: src/vmm/src/devices/virtio/iov_deque.rs
Comment (Manciukic) [inline src/vmm/src/devices/virtio/iov_deque.rs:1]: could you to add a unit test to verify the behaviour when `L < capacity`? For example, using `L=64` and testing a scenario where it was failing before this change

**Comment by louwers** [comment]
Confirmed that this fix seems to solve the problem I reported.

**Review by Manciukic — DISMISSED** [review]

**Comment by Manciukic** [comment]
Build is complaining about some markdown formatting
```
FAILED integration_tests/style/test_markdown.py::test_markdown_style - AssertionError: Some markdown files need formatting. Either run `./tools/devtool sh mdformat .` in the repository root, or apply the above diffs manually.
```

**Review by Manciukic — DISMISSED** [review]

File: CHANGELOG.md [hunk 1]
```diff
@@ -29,6 +29,10 @@ and this project adheres to
 
 ### Fixed
 
+- [#5222](https://github.com/firecracker-microvm/firecracker/pull/5222): Fixed
+  `IovDeque` wraparound logic which prevented it from working properly on
+  systems with non 4K pages.
```
Comment (roypat) [inline CHANGELOG.md:34]: Might be more interesting to say how this bug would appear for a customer, instead of the technical detail we fixed. E.g. something like "fixed a bug affecting systems with non 4K pages where network devices stop working after 256 packets were exchanged"?

**Review by roypat — APPROVED** [review]
