### PR TITLE
micro-http: unsigned Content-Length + several checked arithmetic operations

### LINKED ISSUE #1977: micro-http: validate that the content-length is valid
We are not validating that the content-length is valid when parsing requests via the `connection` module.

One problem is that Content-Length valued is defined to be an `i32`. Valid lengths though are > 0. This is problematic when the headers are parsed as part of the connection module because there we are using `Content-Length` to read from the stream.
As no other bound checks are done, this results in a Firecracker crash. 

## Steps to reproduce

Input:
```bash
curl --unix-socket /tmp/firecracker.sock -i \
    -X GET 'http://localhost/actions' \
    -H 'Accept: application/json' \
    -H 'Content-Length: -1' \
```
Output with debug builds:
```
2020-06-25T12:43:58.057850423 [anonymous-instance:ERROR:src/firecracker/src/main.rs:64] Firecracker panicked at 'attempt to add with overflow', src/micro_http/src/connection.rs:287:37
Aborted (core dumped)
```

### TODO

- [ ] Content-Length type should be changed to something that does not accept negative values (i.e. we can work with u32 instead); The same needs to be applied to 
- [ ] Validate the Content-Length (and all other fields are valid) before doing operations that might result in index out of bounds or overflows. For example, if content-length == 0 -> don't try to read the body.
- [ ] Add negative tests for Content-Length values.

### PR DESCRIPTION
**Pull request by aghecenco**
## Reason for This PR

Fixes #1977

## Description of Changes

* Changed `Content-Length` from `i32` to `u32`.
* Added a bunch of fixes for unchecked unsigned arithmetic in `connection.rs`. 
* Added more unit tests too that exercise failure cases for over/underflows in math operations.
* Replaced some `unwrap`s with error propagation, introducing new error variants.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.

### CODE REVIEW

File: src/micro_http/src/connection.rs [hunk 1]
```diff
@@ -213,16 +242,27 @@ impl<T: Read + Write> HttpConnection<T> {
...
+                        RequestError::HeadersWithoutPendingRequest,
+                    ))?;
                 // The `line_end_index` relative to the whole buffer.
-                let line_end_index = relative_line_end_index + *line_start_index;
+                let line_end_index = relative_line_end_index
+                    .checked_add(*line_start_index)
+                    .ok_or(ConnectionError::ParseError(RequestError::Overflow))?;
 
                 // Get the line slice and parse it.
+                // The slice access is safe becase `line_end_index` is a sum of `line_end_index`
```
Comment (ioanachirca) [inline src/micro_http/src/connection.rs:264]: maybe
```suggestion
                // The slice access is safe because `line_end_index` is a sum of `line_start_index`
```
?

File: src/micro_http/src/connection.rs [hunk 2]
```diff
@@ -265,12 +308,21 @@ impl<T: Read + Write> HttpConnection<T> {
...
+            .ok_or(ConnectionError::ParseError(RequestError::Underflow))?
+            as u32;
+        if self.body_bytes_to_be_read > start_to_end {
             // Append everything that we read to our current incomplete body and update
             // `body_bytes_to_be_read`.
+            // The slice access is safe, otherwise `checked_sub` would have failed.
             self.body_vec
                 .extend_from_slice(&self.buffer[*line_start_index..end_cursor]);
-            self.body_bytes_to_be_read -= end_cursor as i32 - *line_start_index as i32;
+            // Safe to substract directly as the `if` condition prevents underflow.
```
Comment (ioanachirca) [inline src/micro_http/src/connection.rs:324]: nit: 
```suggestion
            // Safe to subtract directly as the `if` condition prevents underflow.
```

File: src/mmds/src/lib.rs [hunk 3]
```diff
@@ -137,6 +137,16 @@ pub fn parse_request(request_bytes: &[u8]) -> Response {
             }
         }
         Err(e) => match e {
+            RequestError::BodyWithoutPendingRequest => build_response(
```
Comment (lauralt) [inline src/mmds/src/lib.rs:140]: The changes in this file will need a small rebase and after that, we should test in `test_parse_request_bytes_error()` also the newly added error types.

File: src/micro_http/src/common/headers.rs [hunk 4]
```diff
@@ -134,7 +134,7 @@ impl Headers {
                 }
                 if let Ok(head) = Header::try_from(entry[0].as_bytes()) {
                     match head {
-                        Header::ContentLength => match entry[1].trim().parse::<i32>() {
+                        Header::ContentLength => match entry[1].trim().parse::<u32>() {
```
Comment (lauralt) [inline src/micro_http/src/common/headers.rs:137]: nit: as a double-check, I would add the following:

```rust
        // Invalid content length.
        assert_eq!(
            header.parse_header_line(b"Content-Length: -1"),
            Err(RequestError::InvalidHeader)
        );
```
in `test_parse_header_line()`, even though this is tested in `connection.rs` too.

File: src/mmds/src/lib.rs (hunk 3 above)
Comment (aghecenco) [reply src/mmds/src/lib.rs]: After rebasing and looking more carefully I realized that the overflow checks I'd added were superfluous, so I documented the safety of the operations instead
