### PR TITLE
Disable unsupported `SendCtrlAltDel` API action on aarch64

### LINKED ISSUE #1340: SendCtrlAltDel API action not supported on ARM
Firecracker does not yet emulate an `i8042` device on `aarch64`, therefore the `SendCtrlAltDel` API action does not work as intended.

Disable the API action on ARM and provide a clear API response until `i8042` support is added (issue #1339).

### PR DESCRIPTION
**Pull request by acatangiu**
## Reason for This PR

Fixes #1340 

## Description of Changes

Firecracker doesn't currently have `i8042` support on `aarch64`. Because of this, disable and provide a clear error message for the `SendCtrlAltDel` API request.
    
Also mark all the port-io code as `x86_64` specific.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`  
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] Either this PR is linked to an issue, or, the reason for this PR is
      clearly provided. 
- [x] The description of changes is clear and encompassing.
- [x] Either no docs need to be updated as part of this PR, or, the required
      doc changes are included in this PR. Docs in scope are all `*.md` files
      located either in the repository root, or in the `docs/` directory.
- [x] Either no code has been touched, or, code-level documentation for touched
      code is included in this PR.
- [ ] Either no API changes are included in this PR, or, the API changes are
      reflected in `firecracker/swagger.yaml`.
- [ ] Either the changes in this PR have no user impact, or, the changes in
      this PR have user impact and have been added to the `CHANGELOG.md` file.

### CODE REVIEW

File: vmm/src/device_manager/legacy.rs [hunk 1]
```diff
@@ -4,6 +4,8 @@
 // Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
 // Use of this source code is governed by a BSD-style license that can be
 // found in the THIRD-PARTY file.
+#![cfg(target_arch = "x86_64")]
```
Comment (serban300) [inline vmm/src/device_manager/legacy.rs]: I'm not completely sure what this means. Is this supposed to prevent this file from compiling on arm ?

If so wouldn't it be better to move this directive to `vmm/src/device_manager/mod.rs` before `pub mod legacy;` ?

File: vmm/src/lib.rs [hunk 2]
```diff
@@ -915,10 +918,19 @@ impl Vmm {
...
-                .map_err(StartMicrovmError::Vcpu)?;
+            let mut vcpu = Vcpu::new(
+                cpu_index,
+                self.vm.fd(),
+                #[cfg(target_arch = "x86_64")]
+                self.vm.supported_cpuid().clone(),
+                #[cfg(target_arch = "x86_64")]
+                io_bus,
+                request_ts.clone(),
+            )
```
Comment (sandreim) [inline vmm/src/lib.rs]: I do not really like functions with variable parameter count based on a compile time switch. It is possible to have 2 separate new functions : new_x86, new_aarch64 or some other way of fixing the variable parameter count.

Comment (acatangiu) [reply vmm/src/lib.rs]: Fine by me, will change unless someone disagrees.

File: vmm/src/device_manager/legacy.rs (hunk 1 above)
Comment (acatangiu) [reply vmm/src/device_manager/legacy.rs]: Yeah, that makes sense, will try it.

File: vmm/src/lib.rs (hunk 2 above)
Comment (sandreim) [reply vmm/src/lib.rs]: @serban300 since you are already reviewing this PR, please comment on this.

Comment (serban300) [reply vmm/src/lib.rs]: I agree. Different constructors for x86 vs aarch64 sound good.

Comment (andreeaflorescu) [reply vmm/src/lib.rs]: Instead of having new_x86 and new_aarch64 you can have two new functions compiled only for the targeted platforms.

Comment (acatangiu) [reply vmm/src/lib.rs]: @andreeaflorescu the original/current version of the code in this PR does that. It provides two `Vcpu::new()` functions with different signatures, each compiled for its respective platform.

**Comment by acatangiu** [comment]
@serban300 @sandreim @andreeaflorescu check out the revised version.
