### PR TITLE
vmm: fix test_epoll_stdin_event

### LINKED ISSUE #1381: test_epoll_stdin_event fails on a1.metal when running without a tty
Running the CI suite over ssh causes `test_epoll_stdin_event` to fail on an [a1.metal](https://aws.amazon.com/ec2/instance-types/a1/) instance.
Running it from a terminal works fine.

```bash
ssh ec2-user@a1.metal 'firecracker/tools/devtool -y test -- integration_tests/build/test_unittests.py'
```

```rust
---- tests::test_epoll_stdin_event stdout ----
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: core::option::Option<T>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/macros.rs:12
  12: vmm::tests::test_epoll_stdin_event
             at vmm/src/lib.rs:2293
  13: vmm::tests::test_epoll_stdin_event::{{closure}}
             at vmm/src/lib.rs:2289
  14: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
  19: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1408
  20: test::run_test::run_test_inner
             at src/libtest/lib.rs:1430
  21: test::run_test
             at src/libtest/lib.rs:1449
  22: test::run_tests
             at src/libtest/lib.rs:1102
  23: test::run_tests_console
             at src/libtest/lib.rs:951
  24: test::test_main
             at src/libtest/lib.rs:294
  25: test::test_main_static
             at src/libtest/lib.rs:328
  26: vmm::main
  27: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  31: std::panicking::try
             at src/libstd/panicking.rs:275
  32: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  33: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  34: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  35: main
  36: __libc_start_main
  37: <unknown>


failures:
    tests::test_epoll_stdin_event

```

### PR DESCRIPTION
**Pull request by dianpopa**
## Reason for This PR

Fixes #1381 

## Description of Changes

This unit tests makes sure that calling
epoll_ctl_add on STDIN_FILENO succeeds.
However, if the unit tests are run through
ssh without a pseudo terminal, adding STDIN_FILENO
would return EPERM. Adjust unit test to not panic
in case of EPERM.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria. Where there are two options, keep one.]`  
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided. 
- [x] The description of changes is clear and encompassing.
- [x] No docs need to be updated as part of this PR.
- [x] Code-level documentation for touched code is included in this PR.
- [x] No API changes are included in this PR.
- [x] The changes in this PR have no user impact.
- [x] No new `unsafe` code has been added.

### CODE REVIEW

File: vmm/src/lib.rs [hunk 1]
```diff
@@ -2267,15 +2267,37 @@ mod tests {
...
-        );
-        // This should trigger a warn!. When logger will not be a global var we will be able to test
-        // it.
-        epoll_context.enable_stdin_event();
 
+        // If this unit test is run without a terminal attached (i.e ssh without pseudo terminal,
+        // request, jailer with `--deamonize` flag on) EPOLL_CTL_ADD would return EPERM
+        // on STDIN_FILENO.
+        // Here we are testing that if we receive EPERM, we are no longer asserting
+        // against `epoll_context.dispatch_table[epoll_context.stdin_index as usize]` holding any value.
```
Comment (andreeaflorescu) [inline vmm/src/lib.rs]: Considering these restrictions, is this test ever going to be run by the CI?

Comment (dianpopa) [reply vmm/src/lib.rs]: Yes, the test is run by the CI both on x86_64 and aarch64.
The x86_64 hits the first branch of the match (i.e `Ok`) while aarch64 hits the EPERM branch.
The other solution to this problem would be to run the tests with `ssh -t` (which allocates a pseudo terminal by force) but i did not choose that path because it contravenes with the `--daemonize` flag where we want firecracker to redirect all three standard I/O file descriptors to dev/null.

Comment (dianpopa) [reply vmm/src/lib.rs]: This is not a new one, it is also described at `https://github.com/firecracker-microvm/firecracker/blob/master/vmm/src/lib.rs#L211`.

Comment (andreeaflorescu) [reply vmm/src/lib.rs]: I see. My worry was that this test can silently fail and hide away problems with our code.

File: vmm/src/lib.rs [hunk 2]
```diff
@@ -2267,15 +2267,37 @@ mod tests {
...
-        assert_eq!(
-            epoll_context.dispatch_table[epoll_context.stdin_index as usize].unwrap(),
-            EpollDispatch::Stdin
-        );
-        // This should trigger a warn!. When logger will not be a global var we will be able to test
-        // it.
-        epoll_context.enable_stdin_event();
 
+        // If this unit test is run without a terminal attached (i.e ssh without pseudo terminal,
+        // request, jailer with `--deamonize` flag on) EPOLL_CTL_ADD would return EPERM
```
Comment (aghecenco) [inline vmm/src/lib.rs]:
```suggestion
        // request, jailer with `--daemonize` flag on) EPOLL_CTL_ADD would return EPERM
```

File: vmm/src/lib.rs [hunk 3]
```diff
@@ -2262,15 +2262,21 @@ mod tests {
...
-            EpollDispatch::Stdin
-        );
-        // This should trigger a warn!. When logger will not be a global var we will be able to test
-        // it.
-        epoll_context.enable_stdin_event();
 
+        // If this unit test is run without a terminal attached (i.e ssh without pseudo terminal,
+        // request, jailer with `--daemonize` flag on) EPOLL_CTL_ADD would return EPERM
+        // on STDIN_FILENO.
+        // Here we are testing that if we receive EPERM, we are no longer asserting
```
Comment (serban300) [inline vmm/src/lib.rs]: The comment looks a bit outdated.

Comment (dianpopa) [reply vmm/src/lib.rs]: Done, take a look.
