### PR TITLE
[aarch64][snap] Reorganizing the GIC registers state

### LINKED ISSUE #2234: [Bug] extend information gathered for the vgic's register
## Describe the bug

For the moment the aarch64 snapshotting functionality #2101  saves the vgic register values in a `Vec`. However, this design might not offer enough information on the registers in situations where we might need to save/restore them in a system that offers a differrent number of maximum supported interrupts. For example if we save on a firecracker version with n IRQs and try to restore on a possible later firecracker version with m IRQs, this will lead to assigning the values to wrong registers when restoring.

### LINKED ISSUE #2239: [Improvement] Improve readability for VGIC' distributor register handling
Right now the code for the distributor registers contains only one list and one type of structure for all distributor registers. For more readability, it would be nice to divide this register into 2 types of register (simple ones and the shared IRQ type).
Any further ideas of readability improvement are welcome.

### PR DESCRIPTION
**Pull request by serban300**
## Reason for This PR

Fixes #2234 
Fixes #2239 

## Description of Changes

- Refactor the logic for saving/restoring GIC regs in order to make it more generic and reusable.
- Reorganizing the GIC registers state. 

Each GIC register has different values for each CPU and can be represented as a `Vec<REG_CHUNK_SIZE>`. So we serialize a list of Registers as `Vec<Vec<Vec<REG_CHUNK_SIZE>>>`. The levels of imbrication signify:
- the list of CPUs
- the list of registers for each CPU
- the data for each register

Before, all this data was compressed in a `Vec<REG_CHUNK_SIZE>` , leading to information loss. For example creating a snapshot on a Firecracker version with 100 IRQs and trying to restore it on a system with 1000 IRQs would have been impossible.

**This is designed as an incremental PR in order to make it easier to be reviewed.** 

Next steps after merging this PR:
- I'm evaluating the option of saving this info inside each VCPU state. This would enable us to remove a level of imbrication (`Vec<Vec<REG_CHUNK_SIZE>>`). Otherwise we would also need to check that the len of the `mpidrs` Vec is equal to the len of `Vec<Vec<Vec<REG_CHUNK_SIZE>>>` 
- creating a separate structure for `Vec<REG_CHUNK_SIZE>`.
- Adding `num_priority_bits` related checks to the ICC regs logic.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] The reason for this PR is clearly provided (issue no. or explanation).
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

### CODE REVIEW

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 1]
```diff
@@ -2,17 +2,132 @@ mod dist_regs;
...
+
+    fn iter<T>(&self) -> StepBy<Range<u64>>
+    where
+        Self: Sized,
+    {
+        self.range().step_by(std::mem::size_of::<T>())
+    }
+}
+
+pub trait VgicRegEngine {
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/mod.rs:24]: Does this trait need to be `pub`? The trait defines many functions (all public because of the trait) of which only `get/set_regs_data` are the ones to be used "publicly".

As a very simple band-aid we could just make the trait `non-pub` and expect the code _inside_ this crate to properly use the trait methods (with no expectations from code external to this crate).

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 2]
```diff
@@ -2,17 +2,132 @@ mod dist_regs;
...
+    fn kvm_device_attr(offset: u64, val: &mut Self::RegChunk, mpidr: u64) -> kvm_device_attr {
+        kvm_device_attr {
+            group: Self::group(),
+            attr: (mpidr & Self::mpidr_mask()) | offset,
+            addr: val as *mut Self::RegChunk as u64,
+            flags: 0,
+        }
+    }
+
+    fn get_reg_data(fd: &DeviceFd, reg: &Self::Reg, mpidr: u64) -> Result<Vec<Self::RegChunk>>
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/mod.rs:41]: nit:
since `get_reg_data()` is not really used on its own, I would inline it in `get_regs_data()` and avoid an extra dynamic dispatch function call.

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 3]
```diff
@@ -2,17 +2,132 @@ mod dist_regs;
...
+    {
+        let mut data = Vec::new();
+        for reg in regs {
+            data.push(Self::get_reg_data(fd, reg, mpidr)?);
+        }
+
+        Ok(data)
+    }
+
+    fn set_reg_data(
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/mod.rs:72]: Same here, maybe inline it in `set_regs_data()`

File: src/arch/src/aarch64/gic/regs/dist_regs.rs [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+    }
+}
+
+impl MmappedReg for DistReg {
+    fn range(&self) -> Range<u64> {
+        let reg: &dyn MmappedReg = match self {
+            DistReg::Simple(reg) => reg,
+            DistReg::SharedIrq(reg) => reg,
+        };
+        reg.range()
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/dist_regs.rs:95]: nit: this should work too, right?
```suggestion
        match self {
            DistReg::Simple(reg) => reg.range(),
            DistReg::SharedIrq(reg) => reg.range(),
        }
```

**Comment by acatangiu** [comment]
Looks good as an intermediary step towards the final gicv3 state representation.

The main missing/still-in-progress things:
 - represent registers using specific types instead of `Vec<u32>`/`Vec<u64>`,
 - move `redist_regs` and `icc_regs` to `vcpu` state since there is per-vcpu state for them in the GIC.

File: src/arch/src/aarch64/gic/regs/dist_regs.rs [hunk 5]
```diff
@@ -147,15 +147,13 @@ fn access_dist_reg_list(fd: &DeviceFd, action: &mut Action) -> Result<()> {
     Ok(())
 }
 
-/// Get distributor registers of the GIC.
 pub fn get_dist_regs(fd: &DeviceFd) -> Result<Vec<u32>> {
```
[the remark this answers is not in the document]
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/dist_regs.rs]: We need the function to be `pub`, otherwise it won't be visible outside the file. But we don't re-export it outside of the `regs` module. 

The crate has `#![deny(missing_docs)]`.

File: src/arch/src/aarch64/gic/regs/dist_regs.rs [hunk 6]
```diff
@@ -39,124 +42,87 @@ static VGIC_DIST_REGS: &[DistReg] = &[
...
-// Helps with triggering either a register fetch or a store.
-enum Action<'a> {
-    Set(&'a [u32], usize),
-    Get(&'a mut Vec<u32>),
+/// Structure representing a shared irq register.
+pub struct SharedIrqReg {
+    /// The offset from the component address. The register is memory mapped here.
+    offset: u64,
+    /// Size in bytes.
+    bits_per_irq: u8,
```
[the remark this answers is not in the document]
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/dist_regs.rs:50]: Fixed.

File: src/arch/src/aarch64/gic/regs/dist_regs.rs (hunk 4 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/dist_regs.rs:95]: Yes. Done.

File: src/arch/src/aarch64/gic/regs/dist_regs.rs [hunk 7]
```diff
@@ -176,7 +142,7 @@ mod tests {
         let res = get_dist_regs(&gic_fd.device_fd());
         assert!(res.is_ok());
         let state = res.unwrap();
-        assert_eq!(state.len(), 245);
+        assert_eq!(state.len(), 12);
```
[the remark this answers is not in the document]
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/dist_regs.rs:145]: Done.

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 1 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/mod.rs:24]: The trait has to be `pub` in order to be used outside of this file. But we don't re-export it outside this module.

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 2 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/mod.rs:41]: Good idea. For the moment I marked it as `inline`. I wouldn't remove the method since we might need to use it in the future. It offers extra flexibility.

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 3 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/mod.rs:72]: Done. Same as for `get_reg_data`.

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 8]
```diff
@@ -2,17 +2,132 @@ mod dist_regs;
...
+            addr: val as *mut Self::RegChunk as u64,
+            flags: 0,
+        }
+    }
+
+    fn get_reg_data(fd: &DeviceFd, reg: &Self::Reg, mpidr: u64) -> Result<Vec<Self::RegChunk>>
+    where
+        Self: Sized,
+    {
+        let mut data = Vec::new();
```
[the remark this answers is not in the document]
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/mod.rs:45]: Done.

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 1 above)
Comment (acatangiu) [reply src/arch/src/aarch64/gic/regs/mod.rs:24]: nit: make these `pub(crate)`

File: src/arch/src/aarch64/gic/regs/dist_regs.rs [hunk 9]
```diff
@@ -0,0 +1,162 @@
...
+        fd,
+        Box::new(VGIC_DIST_REGS.iter()),
+        0,
+    )?)
+}
+
+pub fn set_dist_regs(fd: &DeviceFd, state: &[Vec<u32>]) -> Result<()> {
+    DistRegEngine::set_regs_data(fd, Box::new(VGIC_DIST_REGS.iter()), state, 0)?;
+
+    Ok(())
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/dist_regs.rs:126]: nit:
```suggestion
    DistRegEngine::set_regs_data(fd, Box::new(VGIC_DIST_REGS.iter()), state, 0)
```

File: src/arch/src/aarch64/gic/regs/icc_regs.rs [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+        {
+            return false;
+        }
+
+        true
+    }))
+}
+
+pub fn get_icc_regs(fd: &DeviceFd, mpidrs: &[u64]) -> Result<Vec<VgicSysRegsState>> {
+    let mut state: Vec<VgicSysRegsState> = Vec::new();
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/icc_regs.rs:133]: nit:

```suggestion
    let mut state: Vec<VgicSysRegsState> = Vec::with_capacity(mpidrs.len());
```

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 11]
```diff
@@ -0,0 +1,206 @@
...
+        }
+    }
+
+    #[inline]
+    fn get_reg_data(fd: &DeviceFd, reg: &Self::Reg, mpidr: u64) -> Result<Vec<Self::RegChunk>>
+    where
+        Self: Sized,
+    {
+        let mut data = Vec::with_capacity(reg.iter::<Self::RegChunk>().count());
+        for offset in reg.iter::<Self::RegChunk>() {
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/mod.rs:47]: nit:

don't build iter twice - although most likely the compiler already does this optimization for us anyway

```suggestion
        let iter = reg.iter::<Self::RegChunk>();
        let mut data = Vec::with_capacity(iter.count());
        for offset in iter {
```

File: src/arch/src/aarch64/gic/regs/mod.rs [hunk 12]
```diff
@@ -0,0 +1,206 @@
...
+
+    fn get_regs_data(
+        fd: &DeviceFd,
+        regs: Box<dyn Iterator<Item = &Self::Reg>>,
+        mpidr: u64,
+    ) -> Result<Vec<Vec<Self::RegChunk>>>
+    where
+        Self: Sized,
+    {
+        let mut data = Vec::new();
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/mod.rs:65]: nit:
```suggestion
        let mut data = Vec::with_capacity(regs.len());
```

File: src/arch/src/aarch64/gic/regs/redist_regs.rs [hunk 13]
```diff
@@ -0,0 +1,125 @@
...
+        KVM_DEV_ARM_VGIC_V3_MPIDR_MASK as u64
+    }
+}
+
+fn redist_regs() -> Box<dyn Iterator<Item = &'static SimpleReg>> {
+    Box::new(VGIC_RDIST_REGS.iter().chain(VGIC_SGI_REGS))
+}
+
+pub fn get_redist_regs(fd: &DeviceFd, mpidrs: &[u64]) -> Result<Vec<Vec<Vec<u32>>>> {
+    let mut data = Vec::new();
```
Comment (acatangiu) [inline src/arch/src/aarch64/gic/regs/redist_regs.rs:70]: nit:
```suggestion
    let mut data = Vec::with_capacity(mpidrs.len());
```

**Review by acatangiu — DISMISSED** [review]

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 12 above)
Comment (acatangiu) [reply src/arch/src/aarch64/gic/regs/mod.rs:65]: I think above comment was meant for another thread 😛

File: src/arch/src/aarch64/gic/regs/redist_regs.rs (hunk 13 above)
Comment (acatangiu) [reply src/arch/src/aarch64/gic/regs/redist_regs.rs:70]: nit:
not done

**Review by acatangiu — DISMISSED** [review]

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 12 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/mod.rs:65]: I double checked. It also happens here.

File: src/arch/src/aarch64/gic/regs/redist_regs.rs (hunk 13 above)
Comment (serban300) [reply src/arch/src/aarch64/gic/regs/redist_regs.rs:70]: I don't know why I missed this. You're right. Done now.

**Review by acatangiu — APPROVED** [review]

File: src/arch/src/aarch64/gic/regs/mod.rs (hunk 12 above)
Comment (acatangiu) [reply src/arch/src/aarch64/gic/regs/mod.rs:65]: oooh, getting `len()` using an iterator implies actually running the iterator to its end, which obviously consumes it.

`Vec::with_capacity(regs_iter.clone().len());` should work if the underlying iter supports clone.

This is only a nit anyway, the create snapshot performance is not critical.

**Review by dianpopa — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]
