### PR TITLE
Made Invalid Header error more verbose

### LINKED ISSUE #1976: micro-http: add more flexibility when parsing the headers
When we are parsing headers with micro-http, we expect them to be formatted as follows:

``` ${HEADER_NAME} : SPACE ${HEADER_VALUE}```

This breaks some HTTP clients that are more flexible and don't require a space after ":" in the header definition.

## Steps to reproduce:

Input:
```bash
curl --unix-socket /tmp/firecracker.socket -i \
     -X PUT "http://localhost/machine-config" \
     -H "accept:application/json" \
     -H "Content-Type: application/json" \
     -d "{ 
            \"vcpu_count\": 1, 
            \"mem_size_mib\": 3906, 
            \"ht_enabled\": false
        }"
```
The output is:
```
HTTP/1.1 400 
Server: Firecracker API
Connection: keep-alive
Content-Type: application/json
Content-Length: 80

{ "error": "Invalid header.
All previous unanswered requests will be dropped." }
```

The expected behavior is for the curl request to be successful.

## TODO
- [x] allow both formats for header lines: ``` ${HEADER_NAME} : SPACE ${HEADER_VALUE}``` and ``` ${HEADER_NAME} :  ${HEADER_VALUE}```
- [x] add regression test to validate that both formats work
- [ ] [optional-ish] make the error "Invalid header" a bit more useful. Invalid header can mean a lot of things. When a request is sent with multiple headers, it would be nice to at least print which of the headers is the one that's not correct.

### PR DESCRIPTION
**Pull request by AlexandruCihodaru**
Signed-off-by: cihodar <cihodar@amazon.com>

## Reason for This PR

Fixes #1976
Made the output of InvalidHeader more verbose.

## Description of Changes
 
Modified InvalidHeader error such that it will give more context.

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

File: src/micro_http/src/connection.rs [hunk 1]
```diff
@@ -681,9 +726,17 @@ mod tests {
         request_body.write_all(b"\r\n\r\n").unwrap();
         sender.write_all(request_body.as_slice()).unwrap();
         assert!(conn.try_read().is_ok());
+
+        let mut x = String::with_capacity(1030);
```
Comment (iulianbarbu) [inline src/micro_http/src/connection.rs:730]:
```suggestion
        let mut x = String::new();
```

File: src/micro_http/src/connection.rs [hunk 2]
```diff
@@ -681,9 +726,17 @@ mod tests {
...
+        x.push_str("head: ");
+        let y = String::from_utf8(request_body);
+        x.push_str(&y.unwrap());
```
Comment (iulianbarbu) [inline src/micro_http/src/connection.rs:733]:
```suggestion
        x.push_str(String::from_utf8(request_body).unwrap().as_str());
```

File: src/micro_http/src/connection.rs [hunk 3]
```diff
@@ -288,7 +292,17 @@ impl<T: Read + Write> HttpConnection<T> {
                 // line end sequence.
                 if *line_start_index == 0 && end_cursor == BUFFER_SIZE {
                     // Header line is longer than BUFFER_SIZE bytes, so it is invalid.
-                    return Err(ConnectionError::ParseError(RequestError::InvalidHeader));
+                    if let Ok(utf8_string) = String::from_utf8(self.buffer.to_vec()) {
+                        return Err(ConnectionError::ParseError(RequestError::InvalidHeader(
+                            InvalidHeaderError::SizeLimitExceeded(utf8_string),
```
Comment (iulianbarbu) [inline src/micro_http/src/connection.rs:297]: I do not think `SizeLimitExceeded` is a subcase of `InvalidHeader`. Do you know if HTTP header line/field has maximum 1024 chars, according to the RFC? I was not able to find such limitation and I am inclined to believe that this is just an implementation limitation. I think these limits are configurable for HTTP servers/clients and they are imposed at the level of HTTP requests/response size. If this is the case, we might want to make from `SizeLimitExceeded` a subcase of `RequestError`. Let me know what you think.

Comment (iulianbarbu) [reply src/micro_http/src/connection.rs:297]: Synced offline with @AlexandruCihodaru . We've agreed on having `SizeLimitExceeded` as a subcase for an `HttpHeaderError` parent case, with the mention that this needs also a comment for the `SizeLimitExceeded` error, to underline the fact that it is a `micro-http` limitation rather than a hard limit for header fields.

This is similar to the case of parsing request lines, which is also limited to maximum `BUFFER_SIZE`. Here, the result in an `InvalidRequest` error. This can be further specialized in the future to something like `SizeLimitExceeded` in the context of a more generic `RequestLineError`.

Resolving this for now.

File: src/micro_http/src/connection.rs [hunk 4]
```diff
@@ -681,9 +690,16 @@ mod tests {
...
+        x.push_str("head: ");
+        x.push_str(String::from_utf8(request_body).unwrap().as_str());
+        x = x[0..1024].to_string();
         assert_eq!(
             conn.try_read().unwrap_err(),
-            ConnectionError::ParseError(RequestError::InvalidHeader)
+            ConnectionError::ParseError(RequestError::HeaderError(
+                HttpHeaderError::SizeLimitExceeded(x)
+            ))
         );
```
Comment (serban300) [inline src/micro_http/src/connection.rs:703]: I would do something like:

```
        let expected_msg = &format!("head: {}", String::from_utf8(request_body).unwrap())[..1024];
        assert_eq!(
            conn.try_read().unwrap_err(),
            ConnectionError::ParseError(RequestError::HeaderError(
                HttpHeaderError::SizeLimitExceeded(expected_msg.to_string())
            ))
        );
```

File: src/micro_http/src/connection.rs [hunk 5]
```diff
@@ -890,7 +906,9 @@ mod tests {
             .unwrap();
         assert_eq!(
             conn.try_read().unwrap_err(),
-            ConnectionError::ParseError(RequestError::InvalidHeader)
+            ConnectionError::ParseError(RequestError::HeaderError(
+                HttpHeaderError::UnsupportedValue("Content-Length".to_string(), " -1".to_string())
```
Comment (serban300) [inline src/micro_http/src/connection.rs:910]: -1 looks like an invalid value

File: src/micro_http/src/common/headers.rs [hunk 6]
```diff
@@ -138,43 +143,76 @@ impl Headers {
...
+                                    entry[1].to_string(),
+                                ),
+                            )),
                         },
                         Header::ContentType => {
                             match MediaType::try_from(entry[1].trim().as_bytes()) {
                                 Ok(_) => Ok(()),
-                                Err(_) => Err(RequestError::UnsupportedHeader),
+                                Err(_) => {
+                                    Err(RequestError::HeaderError(HttpHeaderError::InvalidValue(
```
Comment (serban300) [inline src/micro_http/src/common/headers.rs:157]: Probably here we don't know if it's an invalid or an unsupported value. But we could go with unsupported to keep the previous behavior.

File: src/micro_http/src/common/headers.rs [hunk 7]
```diff
@@ -138,43 +143,76 @@ impl Headers {
...
                             }
-                            "identity; q=0" => Err(RequestError::InvalidHeader),
-                            _ => Err(RequestError::UnsupportedHeader),
+                            "identity; q=0" => Err(RequestError::HeaderError(
+                                HttpHeaderError::UnsupportedFeature(
+                                    entry[0].to_string(),
+                                    entry[1].to_string(),
+                                ),
+                            )),
+                            _ => Err(RequestError::HeaderError(HttpHeaderError::InvalidValue(
```
Comment (serban300) [inline src/micro_http/src/common/headers.rs:187]: Probably here we don't know if it's an invalid or an unsupported value. But we could go with unsupported to keep the previous behavior.

File: src/micro_http/src/common/headers.rs [hunk 8]
```diff
@@ -138,43 +143,76 @@ impl Headers {
...
+                            ))),
                         },
                         Header::Expect => match entry[1].trim() {
                             "100-continue" => {
                                 self.expect = true;
                                 Ok(())
                             }
-                            _ => Err(RequestError::InvalidHeader),
+                            _ => Err(RequestError::HeaderError(
+                                HttpHeaderError::UnsupportedFeature(
```
Comment (serban300) [inline src/micro_http/src/common/headers.rs:198]: Probably here we don't know if it's an invalid or an unsupported value. But we could go with Invalid to keep the previous behavior.

File: src/micro_http/src/common/headers.rs [hunk 9]
```diff
@@ -138,43 +143,76 @@ impl Headers {
...
+                                    entry[0].to_string(),
+                                    entry[1].to_string(),
+                                ),
+                            )),
                         },
                         Header::Server => Ok(()),
                     }
                 } else {
-                    Err(RequestError::UnsupportedHeader)
+                    Err(RequestError::HeaderError(HttpHeaderError::InvalidValue(
```
Comment (serban300) [inline src/micro_http/src/common/headers.rs:207]: Probably here we don't know if it's an invalid or an unsupported value. But we could go with unsupported to keep the previous behavior.

File: src/micro_http/src/common/headers.rs [hunk 10]
```diff
@@ -231,7 +269,9 @@ impl Headers {
                     break;
                 }
                 match headers.parse_header_line(header_line.as_bytes()) {
-                    Ok(_) | Err(RequestError::UnsupportedHeader) => continue,
+                    Ok(_) | Err(RequestError::HeaderError(HttpHeaderError::InvalidValue(_, _))) => {
```
Comment (serban300) [inline src/micro_http/src/common/headers.rs:272]: Why match `InvalidValue` here ? From what I understand Unsupported features or values should be ignored and errors related to unsupported headers or values should be propagated.

**Review by iulianbarbu — APPROVED** [review]

**Review by iulianbarbu — APPROVED** [review]

**Review by serban300 — APPROVED** [review]
