### PR TITLE
Fix boot time for AMD guests

### LINKED ISSUE #1017: Fix test_boottime.py failure for AMD
test_boottime.py expects the boot time to be less then 150 ms. On AMD the boot time is around 350 ms. Investigate why this happens.

### PR DESCRIPTION
**Pull request by dianpopa**
## Reason for This PR

Fixes #1017 

## Description of Changes

Newer processors (like the one we run the CI on, AMD EPYC)
have adopted the TSC_DEADLINE_TIMER cpu flag which used to be Intel
specific.

** Please review by commits. Thanks!

- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.

### CODE REVIEW

File: src/cpuid/src/transformer/common.rs [hunk 1]
```diff
@@ -36,7 +36,10 @@ pub fn update_feature_info_entry(
     let max_cpus_per_package = u32::from(common::get_max_cpus_per_package(vm_spec.cpu_count)?);
 
     // X86 hypervisor feature
-    entry.ecx.write_bit(ecx::HYPERVISOR_BITINDEX, true);
+    entry
+        .ecx
+        .write_bit(ecx::TSC_DEADLINE_TIMER_BITINDEX, true)
+        .write_bit(ecx::HYPERVISOR_BITINDEX, true);
```
Comment (serban300) [inline src/cpuid/src/transformer/common.rs:42]: AMD doesn't support this feature. If we enable it in the guest, the boot time we'll decrease, but we'll sacrifice runtime performance. I think it's better to have different expected values for Intel and AMD for the boot performance test.

Comment (dianpopa) [reply src/cpuid/src/transformer/common.rs:42]: Synced offline with Serban. Indeed, different expected values sounds like a good workaround to me.

Comment (dianpopa) [reply src/cpuid/src/transformer/common.rs:42]: I gathered some more info on the TSC_DEADLINE_TIMER. The deadline TSC is fully emulated by KVM even on Intel where this timer is hardware supported. You can check the emulation code for this [here](https://github.com/torvalds/linux/blob/8f02f363f76f99f08117336cfac7f24c76b25be3/arch/x86/kvm/x86.c#L3201). So, whether the hardware supports it or not, is pretty irrelevant given that KVM implements it nevertheless. 
There was actually another bug expressing the same thing here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1724912.
Another thing relevant here is the dmesg output. You can see the following message:
```
[    0.000000] Hypervisor detected: KVM
[    0.000000] tsc: Fast TSC calibration using PIT
```
So after the system detects that is runs under a hypervisor, calibration happens nevertheless. So, this deems this code [redundant](https://github.com/torvalds/linux/blob/9e98c678c2d6ae3a17cb2de55d17f69dddaa231b/arch/x86/kernel/apic/apic.c#L821).
@serban300 please let me know if any info is needed.
Thanks!

Comment (serban300) [reply src/cpuid/src/transformer/common.rs:42]: You're right. Looks like this doesn't lead to any performance penalty. LGTM.

File: CHANGELOG.md [hunk 2]
```diff
@@ -27,12 +27,15 @@
 - Added metrics for the vsock device.
 
 ### Fixed
+
 - Added `--version` flag to both Firecracker and Jailer.
 - Return `405 Method Not Allowed` MMDS response for non HTTP `GET` MMDS
   requests originating from guest.
 - Fixed folder permissions in the jail (#1802).
+- Boot time on AMD achives the desired performance (i.e under 150ms).
```
Comment (aghecenco) [inline CHANGELOG.md:35]:
```suggestion
- Boot time on AMD achieves the desired performance (i.e under 150ms).
```

Comment (dianpopa) [reply CHANGELOG.md]: Done, take a look!
